/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../app/music-app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../app/services/db.service';
import * as import9 from '@angular/core/src/linker/view_container';
import * as import10 from '@angular/material/button/button';
import * as import11 from '../node_modules/@angular/material/button/button.ngfactory';
import * as import12 from '../node_modules/@angular/material/tooltip/tooltip.ngfactory';
import * as import13 from '@angular/material/icon/icon';
import * as import14 from '../node_modules/@angular/material/icon/icon.ngfactory';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from '@angular/material/core/overlay/overlay';
import * as import17 from '@angular/core/src/zone/ng_zone';
import * as import18 from '@angular/material/core/rtl/dir';
import * as import19 from '@angular/material/icon/icon-registry';
import * as import20 from '@angular/material/tooltip/tooltip';
import * as import21 from '@angular/core/src/linker/query_list';
import * as import22 from '../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import23 from '../../app/music/music.component';
import * as import24 from './music/music.component.ngfactory';
import * as import25 from '@angular/core/src/change_detection/change_detection_util';
import * as import26 from '@angular/core/src/linker/template_ref';
import * as import27 from '../../app/services/samples.service';
import * as import28 from '../../app/services/net.service';
import * as import29 from '@angular/common/src/directives/ng_if';
export class Wrapper_MusicAppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.MusicAppComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.MusicAppComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_MusicAppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_MusicAppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.MusicAppComponent>;
  _MusicAppComponent_0_3:Wrapper_MusicAppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MusicAppComponent_Host0,renderType_MusicAppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'musicApp',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_MusicAppComponent0(this.viewUtils,this,0,this._el_0);
    this._MusicAppComponent_0_3 = new Wrapper_MusicAppComponent(this.injectorGet(import8.DBService,this.parentIndex));
    this.compView_0.create(this._MusicAppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._MusicAppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MusicAppComponent) && (0 === requestNodeIndex))) { return this._MusicAppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MusicAppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const MusicAppComponentNgFactory:import7.ComponentFactory<import0.MusicAppComponent> = new import7.ComponentFactory<import0.MusicAppComponent>('musicApp',View_MusicAppComponent_Host0,import0.MusicAppComponent);
const styles_MusicAppComponent:any[] = ([] as any[]);
class View_MusicAppComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _vc_0:import9.ViewContainer;
  compView_0:import1.AppView<import10.MdButton>;
  _MdButton_0_5:import11.Wrapper_MdButton;
  _MdTooltip_0_6:import12.Wrapper_MdTooltip;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import13.MdIcon>;
  _MdIcon_2_3:import14.Wrapper_MdIcon;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_MusicAppComponent1,renderType_MusicAppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray4(4,'md-raised-button','','md-tooltip','pause/resume'),(null as any));
    this._vc_0 = new import9.ViewContainer(0,(null as any),this,this._el_0);
    this.compView_0 = new import11.View_MdButton0(this.viewUtils,this,0,this._el_0);
    this._MdButton_0_5 = new import11.Wrapper_MdButton(new import15.ElementRef(this._el_0),this.renderer);
    this._MdTooltip_0_6 = new import12.Wrapper_MdTooltip(this.parentView.parentView.injectorGet(import16.Overlay,this.parentView.parentIndex),new import15.ElementRef(this._el_0),this._vc_0.vcRef,this.parentView.parentView.injectorGet(import17.NgZone,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import18.Dir,this.parentView.parentIndex,(null as any)));
    this._text_1 = this.renderer.createText((null as any),'\n                         ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,(null as any),'md-icon',new import3.InlineArray2(2,'role','img'),(null as any));
    this.compView_2 = new import14.View_MdIcon0(this.viewUtils,this,2,this._el_2);
    this._MdIcon_2_3 = new import14.Wrapper_MdIcon(new import15.ElementRef(this._el_2),this.renderer,this.parentView.parentView.injectorGet(import19.MdIconRegistry,this.parentView.parentIndex));
    this._text_3 = this.renderer.createText((null as any),'pause',(null as any));
    this.compView_2.create(this._MdIcon_2_3.context);
    this._text_4 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this.compView_0.create(this._MdButton_0_5.context);
    this._el_5 = this.renderer.createTemplateAnchor((null as any),(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray16(16,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any),'longpress',(null as any),'touchend',(null as any),'mouseenter',(null as any),'mouseleave',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_5,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.MdIcon) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MdIcon_2_3.context; }
    if (((token === import10.MdButton) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._MdButton_0_5.context; }
    if (((token === import20.MdTooltip) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._MdTooltip_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = import3.inlineInterpolate(1,'',this.parentView.context.pause_text,'');
    this._MdButton_0_5.check_color(currVal_0_0_0,throwOnChange,false);
    if (this._MdButton_0_5.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    const currVal_0_1_0:any = 'pause/resume';
    this._MdTooltip_0_6.check__deprecatedMessage(currVal_0_1_0,throwOnChange,false);
    this._MdTooltip_0_6.ngDoCheck(this,this._el_0,throwOnChange);
    if (this._MdIcon_2_3.ngDoCheck(this,this._el_2,throwOnChange)) { this.compView_2.markAsCheckOnce(); }
    this._vc_0.detectChangesInNestedViews(throwOnChange);
    this._MdButton_0_5.checkHost(this,this.compView_0,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { this._MdIcon_2_3.context.ngAfterViewChecked(); }
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
    this.compView_0.destroy();
    this.compView_2.destroy();
    this._MdTooltip_0_6.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._vc_0.nativeElement,ctx);
    this._vc_0.visitNestedViewRootNodes(cb,ctx);
    cb(this._el_5,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) {
      cb(this._text_1,ctx);
      cb(this._el_2,ctx);
      cb(this._text_4,ctx);
    }
    if (((nodeIndex == 2) && (ngContentIndex == 0))) { cb(this._text_3,ctx); }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.compView_0.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_0_5.handleEvent(eventName,$event) && result);
    result = (this._MdTooltip_0_6.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.pause()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_MusicAppComponent2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _vc_0:import9.ViewContainer;
  compView_0:import1.AppView<import10.MdButton>;
  _MdButton_0_5:import11.Wrapper_MdButton;
  _MdTooltip_0_6:import12.Wrapper_MdTooltip;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_MusicAppComponent2,renderType_MusicAppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray8(6,'color','accent','md-raised-button','','md-tooltip','METRO OFF'),(null as any));
    this._vc_0 = new import9.ViewContainer(0,(null as any),this,this._el_0);
    this.compView_0 = new import11.View_MdButton0(this.viewUtils,this,0,this._el_0);
    this._MdButton_0_5 = new import11.Wrapper_MdButton(new import15.ElementRef(this._el_0),this.renderer);
    this._MdTooltip_0_6 = new import12.Wrapper_MdTooltip(this.parentView.parentView.injectorGet(import16.Overlay,this.parentView.parentIndex),new import15.ElementRef(this._el_0),this._vc_0.vcRef,this.parentView.parentView.injectorGet(import17.NgZone,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import18.Dir,this.parentView.parentIndex,(null as any)));
    this._text_1 = this.renderer.createText((null as any),' ',(null as any));
    this._text_2 = this.renderer.createText((null as any),'     \n                            ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,(null as any),'img',new import3.InlineArray8(6,'alt','midiin','src','images/tempo.png','style','height: 32px'),(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this.compView_0.create(this._MdButton_0_5.context);
    this._el_5 = this.renderer.createTemplateAnchor((null as any),(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray16(16,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any),'longpress',(null as any),'touchend',(null as any),'mouseenter',(null as any),'mouseleave',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_5,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.MdButton) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._MdButton_0_5.context; }
    if (((token === import20.MdTooltip) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._MdTooltip_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = 'accent';
    this._MdButton_0_5.check_color(currVal_0_0_0,throwOnChange,false);
    if (this._MdButton_0_5.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    const currVal_0_1_0:any = 'METRO OFF';
    this._MdTooltip_0_6.check__deprecatedMessage(currVal_0_1_0,throwOnChange,false);
    this._MdTooltip_0_6.ngDoCheck(this,this._el_0,throwOnChange);
    this._vc_0.detectChangesInNestedViews(throwOnChange);
    this._MdButton_0_5.checkHost(this,this.compView_0,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
    this.compView_0.destroy();
    this._MdTooltip_0_6.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._vc_0.nativeElement,ctx);
    this._vc_0.visitNestedViewRootNodes(cb,ctx);
    cb(this._el_5,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) {
      cb(this._text_1,ctx);
      cb(this._text_2,ctx);
      cb(this._el_3,ctx);
      cb(this._text_4,ctx);
    }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.compView_0.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_0_5.handleEvent(eventName,$event) && result);
    result = (this._MdTooltip_0_6.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.music.metro.active = false)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_MusicAppComponent3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _vc_0:import9.ViewContainer;
  compView_0:import1.AppView<import10.MdButton>;
  _MdButton_0_5:import11.Wrapper_MdButton;
  _MdTooltip_0_6:import12.Wrapper_MdTooltip;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_MusicAppComponent3,renderType_MusicAppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray4(4,'md-raised-button','','md-tooltip','METRO ON'),(null as any));
    this._vc_0 = new import9.ViewContainer(0,(null as any),this,this._el_0);
    this.compView_0 = new import11.View_MdButton0(this.viewUtils,this,0,this._el_0);
    this._MdButton_0_5 = new import11.Wrapper_MdButton(new import15.ElementRef(this._el_0),this.renderer);
    this._MdTooltip_0_6 = new import12.Wrapper_MdTooltip(this.parentView.parentView.injectorGet(import16.Overlay,this.parentView.parentIndex),new import15.ElementRef(this._el_0),this._vc_0.vcRef,this.parentView.parentView.injectorGet(import17.NgZone,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import18.Dir,this.parentView.parentIndex,(null as any)));
    this._text_1 = this.renderer.createText((null as any),'     \n                            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,(null as any),'img',new import3.InlineArray8(6,'alt','midiin','src','images/tempo_off.png','style','height: 32px'),(null as any));
    this._text_3 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this.compView_0.create(this._MdButton_0_5.context);
    this._el_4 = this.renderer.createTemplateAnchor((null as any),(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray16(16,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any),'longpress',(null as any),'touchend',(null as any),'mouseenter',(null as any),'mouseleave',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_4,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.MdButton) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MdButton_0_5.context; }
    if (((token === import20.MdTooltip) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MdTooltip_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._MdButton_0_5.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    const currVal_0_1_0:any = 'METRO ON';
    this._MdTooltip_0_6.check__deprecatedMessage(currVal_0_1_0,throwOnChange,false);
    this._MdTooltip_0_6.ngDoCheck(this,this._el_0,throwOnChange);
    this._vc_0.detectChangesInNestedViews(throwOnChange);
    this._MdButton_0_5.checkHost(this,this.compView_0,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
    this.compView_0.destroy();
    this._MdTooltip_0_6.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._vc_0.nativeElement,ctx);
    this._vc_0.visitNestedViewRootNodes(cb,ctx);
    cb(this._el_4,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) {
      cb(this._text_1,ctx);
      cb(this._el_2,ctx);
      cb(this._text_3,ctx);
    }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.compView_0.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_0_5.handleEvent(eventName,$event) && result);
    result = (this._MdTooltip_0_6.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.music.metro.active = true)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_MusicAppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_MusicAppComponent,{});
export class View_MusicAppComponent0 extends import1.AppView<import0.MusicAppComponent> {
  _viewQuery_MusicComponent_0:import21.QueryList<any>;
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  /*private*/ _vc_7:import9.ViewContainer;
  compView_7:import1.AppView<import10.MdButton>;
  _MdButton_7_5:import11.Wrapper_MdButton;
  _MdTooltip_7_6:import12.Wrapper_MdTooltip;
  _text_8:any;
  _el_9:any;
  compView_9:import1.AppView<import13.MdIcon>;
  _MdIcon_9_3:import14.Wrapper_MdIcon;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _vc_13:import9.ViewContainer;
  _TemplateRef_13_5:any;
  _NgIf_13_6:import22.Wrapper_NgIf;
  _text_14:any;
  _el_15:any;
  /*private*/ _vc_15:import9.ViewContainer;
  compView_15:import1.AppView<import10.MdButton>;
  _MdButton_15_5:import11.Wrapper_MdButton;
  _MdTooltip_15_6:import12.Wrapper_MdTooltip;
  _text_16:any;
  _el_17:any;
  compView_17:import1.AppView<import13.MdIcon>;
  _MdIcon_17_3:import14.Wrapper_MdIcon;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _anchor_22:any;
  /*private*/ _vc_22:import9.ViewContainer;
  _TemplateRef_22_5:any;
  _NgIf_22_6:import22.Wrapper_NgIf;
  _text_23:any;
  _anchor_24:any;
  /*private*/ _vc_24:import9.ViewContainer;
  _TemplateRef_24_5:any;
  _NgIf_24_6:import22.Wrapper_NgIf;
  _text_25:any;
  _el_26:any;
  /*private*/ _vc_26:import9.ViewContainer;
  compView_26:import1.AppView<import10.MdButton>;
  _MdButton_26_5:import11.Wrapper_MdButton;
  _MdTooltip_26_6:import12.Wrapper_MdTooltip;
  _text_27:any;
  _el_28:any;
  compView_28:import1.AppView<import13.MdIcon>;
  _MdIcon_28_3:import14.Wrapper_MdIcon;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  compView_35:import1.AppView<import23.MusicComponent>;
  _MusicComponent_35_3:import24.Wrapper_MusicComponent;
  _text_36:any;
  _text_37:any;
  /*private*/ _expr_68:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MusicAppComponent0,renderType_MusicAppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_68 = import25.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._viewQuery_MusicComponent_0 = new import21.QueryList<any>();
    this._text_0 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'style','width: 100%'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n  			',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','button-row'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'div',new import3.InlineArray2(2,'class','btn-group'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n                    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'button',new import3.InlineArray2(2,'md-raised-button',''),(null as any));
    this._vc_7 = new import9.ViewContainer(7,5,this,this._el_7);
    this.compView_7 = new import11.View_MdButton0(this.viewUtils,this,7,this._el_7);
    this._MdButton_7_5 = new import11.Wrapper_MdButton(new import15.ElementRef(this._el_7),this.renderer);
    this._MdTooltip_7_6 = new import12.Wrapper_MdTooltip(this.parentView.injectorGet(import16.Overlay,this.parentIndex),new import15.ElementRef(this._el_7),this._vc_7.vcRef,this.parentView.injectorGet(import17.NgZone,this.parentIndex),this.parentView.injectorGet(import18.Dir,this.parentIndex,(null as any)));
    this._text_8 = this.renderer.createText((null as any),'     \n                          ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,(null as any),'md-icon',new import3.InlineArray2(2,'role','img'),(null as any));
    this.compView_9 = new import14.View_MdIcon0(this.viewUtils,this,9,this._el_9);
    this._MdIcon_9_3 = new import14.Wrapper_MdIcon(new import15.ElementRef(this._el_9),this.renderer,this.parentView.injectorGet(import19.MdIconRegistry,this.parentIndex));
    this._text_10 = this.renderer.createText((null as any),'',(null as any));
    this.compView_9.create(this._MdIcon_9_3.context);
    this._text_11 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this.compView_7.create(this._MdButton_7_5.context);
    this._text_12 = this.renderer.createText(this._el_5,'\n                    \n                    ',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor(this._el_5,(null as any));
    this._vc_13 = new import9.ViewContainer(13,5,this,this._anchor_13);
    this._TemplateRef_13_5 = new import26.TemplateRef_(this,13,this._anchor_13);
    this._NgIf_13_6 = new import22.Wrapper_NgIf(this._vc_13.vcRef,this._TemplateRef_13_5);
    this._text_14 = this.renderer.createText(this._el_5,'\n                     \n                    ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_5,'button',new import3.InlineArray8(6,'md-raised-button','','md-tooltip','START RECORDING','style','color:#FF0000;'),(null as any));
    this._vc_15 = new import9.ViewContainer(15,5,this,this._el_15);
    this.compView_15 = new import11.View_MdButton0(this.viewUtils,this,15,this._el_15);
    this._MdButton_15_5 = new import11.Wrapper_MdButton(new import15.ElementRef(this._el_15),this.renderer);
    this._MdTooltip_15_6 = new import12.Wrapper_MdTooltip(this.parentView.injectorGet(import16.Overlay,this.parentIndex),new import15.ElementRef(this._el_15),this._vc_15.vcRef,this.parentView.injectorGet(import17.NgZone,this.parentIndex),this.parentView.injectorGet(import18.Dir,this.parentIndex,(null as any)));
    this._text_16 = this.renderer.createText((null as any),'     \n                          ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,(null as any),'md-icon',new import3.InlineArray2(2,'role','img'),(null as any));
    this.compView_17 = new import14.View_MdIcon0(this.viewUtils,this,17,this._el_17);
    this._MdIcon_17_3 = new import14.Wrapper_MdIcon(new import15.ElementRef(this._el_17),this.renderer,this.parentView.injectorGet(import19.MdIconRegistry,this.parentIndex));
    this._text_18 = this.renderer.createText((null as any),'fiber_manual_record',(null as any));
    this.compView_17.create(this._MdIcon_17_3.context);
    this._text_19 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this.compView_15.create(this._MdButton_15_5.context);
    this._text_20 = this.renderer.createText(this._el_5,'\n                    \n                     ',(null as any));
    this._text_21 = this.renderer.createText(this._el_5,'\n\n					        \n                  	',(null as any));
    this._anchor_22 = this.renderer.createTemplateAnchor(this._el_5,(null as any));
    this._vc_22 = new import9.ViewContainer(22,5,this,this._anchor_22);
    this._TemplateRef_22_5 = new import26.TemplateRef_(this,22,this._anchor_22);
    this._NgIf_22_6 = new import22.Wrapper_NgIf(this._vc_22.vcRef,this._TemplateRef_22_5);
    this._text_23 = this.renderer.createText(this._el_5,'\n                \n				  	',(null as any));
    this._anchor_24 = this.renderer.createTemplateAnchor(this._el_5,(null as any));
    this._vc_24 = new import9.ViewContainer(24,5,this,this._anchor_24);
    this._TemplateRef_24_5 = new import26.TemplateRef_(this,24,this._anchor_24);
    this._NgIf_24_6 = new import22.Wrapper_NgIf(this._vc_24.vcRef,this._TemplateRef_24_5);
    this._text_25 = this.renderer.createText(this._el_5,'\n                    \n                \n                    ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_5,'button',new import3.InlineArray8(6,'md-raised-button','','md-tooltip','SAVEX','style','float: right'),(null as any));
    this._vc_26 = new import9.ViewContainer(26,5,this,this._el_26);
    this.compView_26 = new import11.View_MdButton0(this.viewUtils,this,26,this._el_26);
    this._MdButton_26_5 = new import11.Wrapper_MdButton(new import15.ElementRef(this._el_26),this.renderer);
    this._MdTooltip_26_6 = new import12.Wrapper_MdTooltip(this.parentView.injectorGet(import16.Overlay,this.parentIndex),new import15.ElementRef(this._el_26),this._vc_26.vcRef,this.parentView.injectorGet(import17.NgZone,this.parentIndex),this.parentView.injectorGet(import18.Dir,this.parentIndex,(null as any)));
    this._text_27 = this.renderer.createText((null as any),'\n                       ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,(null as any),'md-icon',new import3.InlineArray2(2,'role','img'),(null as any));
    this.compView_28 = new import14.View_MdIcon0(this.viewUtils,this,28,this._el_28);
    this._MdIcon_28_3 = new import14.Wrapper_MdIcon(new import15.ElementRef(this._el_28),this.renderer,this.parentView.injectorGet(import19.MdIconRegistry,this.parentIndex));
    this._text_29 = this.renderer.createText((null as any),'save',(null as any));
    this.compView_28.create(this._MdIcon_28_3.context);
    this._text_30 = this.renderer.createText((null as any),' \n                    ',(null as any));
    this.compView_26.create(this._MdButton_26_5.context);
    this._text_31 = this.renderer.createText(this._el_5,'\n                ',(null as any));
    this._text_32 = this.renderer.createText(this._el_3,'\n         	',(null as any));
    this._text_33 = this.renderer.createText(this._el_1,'\n     	',(null as any));
    this._text_34 = this.renderer.createText(parentRenderNode,'\n\n     \n     	',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,parentRenderNode,'music',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_35 = new import24.View_MusicComponent0(this.viewUtils,this,35,this._el_35);
    this._MusicComponent_35_3 = new import24.Wrapper_MusicComponent(this.parentView.injectorGet(import8.DBService,this.parentIndex),this.parentView.injectorGet(import27.SamplesService,this.parentIndex),this.parentView.injectorGet(import28.NetService,this.parentIndex));
    this._text_36 = this.renderer.createText((null as any),' ',(null as any));
    this.compView_35.create(this._MusicComponent_35_3.context);
    this._text_37 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_7,new import3.InlineArray16(16,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any),'longpress',(null as any),'touchend',(null as any),'mouseenter',(null as any),'mouseleave',(null as any)),this.eventHandler(this.handleEvent_7));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_15,new import3.InlineArray16(16,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any),'longpress',(null as any),'touchend',(null as any),'mouseenter',(null as any),'mouseleave',(null as any)),this.eventHandler(this.handleEvent_15));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_26,new import3.InlineArray16(16,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any),'longpress',(null as any),'touchend',(null as any),'mouseenter',(null as any),'mouseleave',(null as any)),this.eventHandler(this.handleEvent_26));
    this._viewQuery_MusicComponent_0.reset([this._MusicComponent_35_3.context]);
    this.context.music = this._viewQuery_MusicComponent_0.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._anchor_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._anchor_22,
      this._text_23,
      this._anchor_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.MdIcon) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._MdIcon_9_3.context; }
    if (((token === import10.MdButton) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._MdButton_7_5.context; }
    if (((token === import20.MdTooltip) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._MdTooltip_7_6.context; }
    if (((token === import26.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import29.NgIf) && (13 === requestNodeIndex))) { return this._NgIf_13_6.context; }
    if (((token === import13.MdIcon) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._MdIcon_17_3.context; }
    if (((token === import10.MdButton) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._MdButton_15_5.context; }
    if (((token === import20.MdTooltip) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._MdTooltip_15_6.context; }
    if (((token === import26.TemplateRef) && (22 === requestNodeIndex))) { return this._TemplateRef_22_5; }
    if (((token === import29.NgIf) && (22 === requestNodeIndex))) { return this._NgIf_22_6.context; }
    if (((token === import26.TemplateRef) && (24 === requestNodeIndex))) { return this._TemplateRef_24_5; }
    if (((token === import29.NgIf) && (24 === requestNodeIndex))) { return this._NgIf_24_6.context; }
    if (((token === import13.MdIcon) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._MdIcon_28_3.context; }
    if (((token === import10.MdButton) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._MdButton_26_5.context; }
    if (((token === import20.MdTooltip) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._MdTooltip_26_6.context; }
    if (((token === import23.MusicComponent) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._MusicComponent_35_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._MdButton_7_5.ngDoCheck(this,this._el_7,throwOnChange)) { this.compView_7.markAsCheckOnce(); }
    const currVal_7_1_0:any = import3.inlineInterpolate(1,'',this.context.playstopTip,'');
    this._MdTooltip_7_6.check__deprecatedMessage(currVal_7_1_0,throwOnChange,false);
    this._MdTooltip_7_6.ngDoCheck(this,this._el_7,throwOnChange);
    if (this._MdIcon_9_3.ngDoCheck(this,this._el_9,throwOnChange)) { this.compView_9.markAsCheckOnce(); }
    const currVal_13_0_0:any = this.context.pauseable;
    this._NgIf_13_6.check_ngIf(currVal_13_0_0,throwOnChange,false);
    this._NgIf_13_6.ngDoCheck(this,this._anchor_13,throwOnChange);
    const currVal_15_0_0:any = import3.inlineInterpolate(1,'',this.context.recordColor,'');
    this._MdButton_15_5.check_color(currVal_15_0_0,throwOnChange,false);
    if (this._MdButton_15_5.ngDoCheck(this,this._el_15,throwOnChange)) { this.compView_15.markAsCheckOnce(); }
    const currVal_15_1_0:any = 'START RECORDING';
    this._MdTooltip_15_6.check__deprecatedMessage(currVal_15_1_0,throwOnChange,false);
    this._MdTooltip_15_6.ngDoCheck(this,this._el_15,throwOnChange);
    if (this._MdIcon_17_3.ngDoCheck(this,this._el_17,throwOnChange)) { this.compView_17.markAsCheckOnce(); }
    const currVal_22_0_0:any = (this.context.music && this.context.music.metro.active);
    this._NgIf_22_6.check_ngIf(currVal_22_0_0,throwOnChange,false);
    this._NgIf_22_6.ngDoCheck(this,this._anchor_22,throwOnChange);
    const currVal_24_0_0:any = (this.context.music && !this.context.music.metro.active);
    this._NgIf_24_6.check_ngIf(currVal_24_0_0,throwOnChange,false);
    this._NgIf_24_6.ngDoCheck(this,this._anchor_24,throwOnChange);
    if (this._MdButton_26_5.ngDoCheck(this,this._el_26,throwOnChange)) { this.compView_26.markAsCheckOnce(); }
    const currVal_26_1_0:any = 'SAVEX';
    this._MdTooltip_26_6.check__deprecatedMessage(currVal_26_1_0,throwOnChange,false);
    this._MdTooltip_26_6.ngDoCheck(this,this._el_26,throwOnChange);
    if (this._MdIcon_28_3.ngDoCheck(this,this._el_28,throwOnChange)) { this.compView_28.markAsCheckOnce(); }
    this._MusicComponent_35_3.ngDoCheck(this,this._el_35,throwOnChange);
    this._vc_7.detectChangesInNestedViews(throwOnChange);
    this._vc_13.detectChangesInNestedViews(throwOnChange);
    this._vc_15.detectChangesInNestedViews(throwOnChange);
    this._vc_22.detectChangesInNestedViews(throwOnChange);
    this._vc_24.detectChangesInNestedViews(throwOnChange);
    this._vc_26.detectChangesInNestedViews(throwOnChange);
    this._MdButton_7_5.checkHost(this,this.compView_7,this._el_7,throwOnChange);
    const currVal_68:any = import3.inlineInterpolate(1,' ',this.context.play_stop_icon,' ');
    if (import3.checkBinding(throwOnChange,this._expr_68,currVal_68)) {
      this.renderer.setText(this._text_10,currVal_68);
      this._expr_68 = currVal_68;
    }
    this._MdButton_15_5.checkHost(this,this.compView_15,this._el_15,throwOnChange);
    this._MdButton_26_5.checkHost(this,this.compView_26,this._el_26,throwOnChange);
    this.compView_7.internalDetectChanges(throwOnChange);
    this.compView_9.internalDetectChanges(throwOnChange);
    this.compView_15.internalDetectChanges(throwOnChange);
    this.compView_17.internalDetectChanges(throwOnChange);
    this.compView_26.internalDetectChanges(throwOnChange);
    this.compView_28.internalDetectChanges(throwOnChange);
    this.compView_35.internalDetectChanges(throwOnChange);
    if (!throwOnChange) {
      this._MdIcon_9_3.context.ngAfterViewChecked();
      this._MdIcon_17_3.context.ngAfterViewChecked();
      this._MdIcon_28_3.context.ngAfterViewChecked();
    }
  }
  destroyInternal():void {
    this._vc_7.destroyNestedViews();
    this._vc_13.destroyNestedViews();
    this._vc_15.destroyNestedViews();
    this._vc_22.destroyNestedViews();
    this._vc_24.destroyNestedViews();
    this._vc_26.destroyNestedViews();
    this.compView_7.destroy();
    this.compView_9.destroy();
    this.compView_15.destroy();
    this.compView_17.destroy();
    this.compView_26.destroy();
    this.compView_28.destroy();
    this.compView_35.destroy();
    this._MdTooltip_7_6.ngOnDestroy();
    this._MdTooltip_15_6.ngOnDestroy();
    this._MdTooltip_26_6.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 7) && (ngContentIndex == 0))) {
      cb(this._text_8,ctx);
      cb(this._el_9,ctx);
      cb(this._text_11,ctx);
    }
    if (((nodeIndex == 9) && (ngContentIndex == 0))) { cb(this._text_10,ctx); }
    if (((nodeIndex == 15) && (ngContentIndex == 0))) {
      cb(this._text_16,ctx);
      cb(this._el_17,ctx);
      cb(this._text_19,ctx);
    }
    if (((nodeIndex == 17) && (ngContentIndex == 0))) { cb(this._text_18,ctx); }
    if (((nodeIndex == 26) && (ngContentIndex == 0))) {
      cb(this._text_27,ctx);
      cb(this._el_28,ctx);
      cb(this._text_30,ctx);
    }
    if (((nodeIndex == 28) && (ngContentIndex == 0))) { cb(this._text_29,ctx); }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 13)) { return new View_MusicAppComponent1(this.viewUtils,this,13,this._anchor_13,this._vc_13); }
    if ((nodeIndex == 22)) { return new View_MusicAppComponent2(this.viewUtils,this,22,this._anchor_22,this._vc_22); }
    if ((nodeIndex == 24)) { return new View_MusicAppComponent3(this.viewUtils,this,24,this._anchor_24,this._vc_24); }
    return (null as any);
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.compView_7.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_7_5.handleEvent(eventName,$event) && result);
    result = (this._MdTooltip_7_6.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.play()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_15(eventName:string,$event:any):boolean {
    this.compView_15.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_15_5.handleEvent(eventName,$event) && result);
    result = (this._MdTooltip_15_6.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.record()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_26(eventName:string,$event:any):boolean {
    this.compView_26.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_26_5.handleEvent(eventName,$event) && result);
    result = (this._MdTooltip_26_6.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.save()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}