/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/music/ai-detail.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@angular/material/select/option';
import * as import10 from '../../node_modules/@angular/material/select/option.ngfactory';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '@angular/core/src/linker/element_ref';
import * as import13 from '@angular/material/card/card';
import * as import14 from '../../node_modules/@angular/material/card/card.ngfactory';
import * as import15 from '@angular/material/select/select';
import * as import16 from '../../node_modules/@angular/material/select/select.ngfactory';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import19 from '@angular/material/input/input';
import * as import20 from '../../node_modules/@angular/material/input/input.ngfactory';
import * as import21 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import22 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import23 from '@angular/material/button/button';
import * as import24 from '../../node_modules/@angular/material/button/button.ngfactory';
import * as import25 from '@angular/material/core/overlay/position/viewport-ruler';
import * as import26 from '@angular/material/core/rtl/dir';
import * as import27 from '@angular/forms/src/directives/ng_control';
import * as import28 from '@angular/core/src/linker/template_ref';
import * as import29 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import30 from '@angular/common/src/directives/ng_for';
import * as import31 from '@angular/forms/src/directives/control_value_accessor';
import * as import32 from '@angular/forms/src/directives/ng_model';
import * as import33 from '@angular/forms/src/directives/ng_control_status';
import * as import34 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import35 from '@angular/common/src/directives/ng_if';
export class Wrapper_AIDetailComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AIDetailComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  constructor() {
    this._changed = false;
    this.context = new import0.AIDetailComponent();
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_ai(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.ai = currValue;
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AIDetailComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_AIDetailComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.AIDetailComponent>;
  _AIDetailComponent_0_3:Wrapper_AIDetailComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AIDetailComponent_Host0,renderType_AIDetailComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ai-detail',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AIDetailComponent0(this.viewUtils,this,0,this._el_0);
    this._AIDetailComponent_0_3 = new Wrapper_AIDetailComponent();
    this.compView_0.create(this._AIDetailComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._AIDetailComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AIDetailComponent) && (0 === requestNodeIndex))) { return this._AIDetailComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AIDetailComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AIDetailComponentNgFactory:import8.ComponentFactory<import0.AIDetailComponent> = new import8.ComponentFactory<import0.AIDetailComponent>('ai-detail',View_AIDetailComponent_Host0,import0.AIDetailComponent);
const styles_AIDetailComponent:any[] = ([] as any[]);
class View_AIDetailComponent2 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import9.MdOption>;
  _MdOption_0_3:import10.Wrapper_MdOption;
  _text_1:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_AIDetailComponent2,renderType_AIDetailComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_4 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'md-option',new import3.InlineArray2(2,'role','option'),(null as any));
    this.compView_0 = new import10.View_MdOption0(this.viewUtils,this,0,this._el_0);
    this._MdOption_0_3 = new import10.Wrapper_MdOption(new import12.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText((null as any),'',(null as any));
    this.compView_0.create(this._MdOption_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray4(4,'click',(null as any),'keydown',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.MdOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._MdOption_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.$implicit;
    this._MdOption_0_3.check_value(currVal_0_0_0,throwOnChange,false);
    this._MdOption_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._MdOption_0_3.checkHost(this,this.compView_0,this._el_0,throwOnChange);
    const currVal_4:any = import3.inlineInterpolate(1,'\n                      ',this.context.$implicit,'\n                  ');
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_1,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<View_AIDetailComponent1>this.parentView)._query_MdOption_6_0.setDirty();
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._MdOption_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) { cb(this._text_1,ctx); }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.compView_0.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdOption_0_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_AIDetailComponent1 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import2.AppView<import13.MdCard>;
  _MdCard_2_3:import14.Wrapper_MdCard;
  _text_3:any;
  _el_4:any;
  _MdCardActions_4_3:import14.Wrapper_MdCardActions;
  _text_5:any;
  _el_6:any;
  compView_6:import2.AppView<import15.MdSelect>;
  _MdSelect_6_3:import16.Wrapper_MdSelect;
  _query_MdOption_6_0:import17.QueryList<any>;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _vc_8:import11.ViewContainer;
  _TemplateRef_8_5:any;
  _NgFor_8_6:import18.Wrapper_NgFor;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  compView_11:import2.AppView<import19.MdInput>;
  _MdInput_11_3:import20.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_11_4:any[];
  _NgModel_11_5:import21.Wrapper_NgModel;
  _NgControl_11_6:any;
  _NgControlStatus_11_7:import22.Wrapper_NgControlStatus;
  _query_MdPlaceholder_11_0:import17.QueryList<any>;
  _query_MdHint_11_1:import17.QueryList<any>;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  compView_14:import2.AppView<import23.MdButton>;
  _MdButton_14_3:import24.Wrapper_MdButton;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  compView_17:import2.AppView<import23.MdButton>;
  _MdButton_17_3:import24.Wrapper_MdButton;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_AIDetailComponent1,renderType_AIDetailComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n      ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'md-card',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import14.View_MdCard0(this.viewUtils,this,2,this._el_2);
    this._MdCard_2_3 = new import14.Wrapper_MdCard();
    this._text_3 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,(null as any),'md-card-actions',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardActions_4_3 = new import14.Wrapper_MdCardActions();
    this._text_5 = this.renderer.createText(this._el_4,'\n              ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'md-select',new import3.InlineArray4(4,'placeholder','Net type','role','listbox'),(null as any));
    this.compView_6 = new import16.View_MdSelect0(this.viewUtils,this,6,this._el_6);
    this._MdSelect_6_3 = new import16.Wrapper_MdSelect(new import12.ElementRef(this._el_6),this.renderer,this.parentView.injectorGet(import25.ViewportRuler,this.parentIndex),this.parentView.injectorGet(import26.Dir,this.parentIndex,(null as any)),this.parentView.injectorGet(import27.NgControl,this.parentIndex,(null as any)));
    this._query_MdOption_6_0 = new import17.QueryList<any>();
    this._text_7 = this.renderer.createText((null as any),'\n                  ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_8 = new import11.ViewContainer(8,6,this,this._anchor_8);
    this._TemplateRef_8_5 = new import28.TemplateRef_(this,8,this._anchor_8);
    this._NgFor_8_6 = new import18.Wrapper_NgFor(this._vc_8.vcRef,this._TemplateRef_8_5,this.parentView.injectorGet(import29.IterableDiffers,this.parentIndex),this.parentView.ref);
    this._text_9 = this.renderer.createText((null as any),'\n              ',(null as any));
    this.compView_6.create(this._MdSelect_6_3.context);
    this._text_10 = this.renderer.createText(this._el_4,'\n              ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_4,'md-input',new import3.InlineArray16(12,'id','n_hidden','max','300','min','1','placeholder','Hidden','type','number','value','20'),(null as any));
    this.compView_11 = new import20.View_MdInput0(this.viewUtils,this,11,this._el_11);
    this._MdInput_11_3 = new import20.Wrapper_MdInput(new import12.ElementRef(this._el_11),this.renderer);
    this._NG_VALUE_ACCESSOR_11_4 = [this._MdInput_11_3.context];
    this._NgModel_11_5 = new import21.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_11_4);
    this._NgControl_11_6 = this._NgModel_11_5.context;
    this._NgControlStatus_11_7 = new import22.Wrapper_NgControlStatus(this._NgControl_11_6);
    this._query_MdPlaceholder_11_0 = new import17.QueryList<any>();
    this._query_MdHint_11_1 = new import17.QueryList<any>();
    this._text_12 = this.renderer.createText((null as any),' ',(null as any));
    this.compView_11.create(this._MdInput_11_3.context);
    this._text_13 = this.renderer.createText(this._el_4,'\n              ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_4,'button',new import3.InlineArray2(2,'md-raised-button',''),(null as any));
    this.compView_14 = new import24.View_MdButton0(this.viewUtils,this,14,this._el_14);
    this._MdButton_14_3 = new import24.Wrapper_MdButton(new import12.ElementRef(this._el_14),this.renderer);
    this._text_15 = this.renderer.createText((null as any),'Implant',(null as any));
    this.compView_14.create(this._MdButton_14_3.context);
    this._text_16 = this.renderer.createText(this._el_4,'\n              ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_4,'button',new import3.InlineArray2(2,'md-raised-button',''),(null as any));
    this.compView_17 = new import24.View_MdButton0(this.viewUtils,this,17,this._el_17);
    this._MdButton_17_3 = new import24.Wrapper_MdButton(new import12.ElementRef(this._el_17),this.renderer);
    this._text_18 = this.renderer.createText((null as any),'Save',(null as any));
    this.compView_17.create(this._MdButton_17_3.context);
    this._text_19 = this.renderer.createText(this._el_4,'\n          ',(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n      ',(null as any));
    this.compView_2.create(this._MdCard_2_3.context);
    this._text_21 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_6,new import3.InlineArray4(4,'keydown',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_6));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_11,new import3.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_11));
    this._NgModel_11_5.subscribe(this,this.eventHandler(this.handleEvent_11),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_14,new import3.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_14));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_17,new import3.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_17));
    this._query_MdPlaceholder_11_0.reset(([] as any[]));
    this._MdInput_11_3.context._placeholderChild = this._query_MdPlaceholder_11_0.first;
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import28.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import30.NgFor) && (8 === requestNodeIndex))) { return this._NgFor_8_6.context; }
    if (((token === import15.MdSelect) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._MdSelect_6_3.context; }
    if (((token === import19.MdInput) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._MdInput_11_3.context; }
    if (((token === import31.NG_VALUE_ACCESSOR) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NG_VALUE_ACCESSOR_11_4; }
    if (((token === import32.NgModel) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgModel_11_5.context; }
    if (((token === import27.NgControl) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgControl_11_6; }
    if (((token === import33.NgControlStatus) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgControlStatus_11_7.context; }
    if (((token === import23.MdButton) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._MdButton_14_3.context; }
    if (((token === import23.MdButton) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._MdButton_17_3.context; }
    if (((token === import13.MdCardActions) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._MdCardActions_4_3.context; }
    if (((token === import13.MdCard) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._MdCard_2_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._MdCard_2_3.ngDoCheck(this,this._el_2,throwOnChange)) { this.compView_2.markAsCheckOnce(); }
    this._MdCardActions_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    const currVal_6_0_0:any = 'Net type';
    this._MdSelect_6_3.check_placeholder(currVal_6_0_0,throwOnChange,false);
    this._MdSelect_6_3.ngDoCheck(this,this._el_6,throwOnChange);
    const currVal_8_0_0:any = this.parentView.context.ai.types;
    this._NgFor_8_6.check_ngForOf(currVal_8_0_0,throwOnChange,false);
    this._NgFor_8_6.ngDoCheck(this,this._anchor_8,throwOnChange);
    const currVal_11_0_0:any = 'n_hidden';
    this._MdInput_11_3.check_id(currVal_11_0_0,throwOnChange,false);
    const currVal_11_0_1:any = '300';
    this._MdInput_11_3.check_max(currVal_11_0_1,throwOnChange,false);
    const currVal_11_0_2:any = '1';
    this._MdInput_11_3.check_min(currVal_11_0_2,throwOnChange,false);
    const currVal_11_0_3:any = 'Hidden';
    this._MdInput_11_3.check_placeholder(currVal_11_0_3,throwOnChange,false);
    const currVal_11_0_4:any = 'number';
    this._MdInput_11_3.check_type(currVal_11_0_4,throwOnChange,false);
    const currVal_11_0_5:any = '20';
    this._MdInput_11_3.check_value(currVal_11_0_5,throwOnChange,false);
    this._MdInput_11_3.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_11_1_0:any = this.parentView.context.nHidden;
    this._NgModel_11_5.check_model(currVal_11_1_0,throwOnChange,false);
    this._NgModel_11_5.ngDoCheck(this,this._el_11,throwOnChange);
    this._NgControlStatus_11_7.ngDoCheck(this,this._el_11,throwOnChange);
    if (this._MdButton_14_3.ngDoCheck(this,this._el_14,throwOnChange)) { this.compView_14.markAsCheckOnce(); }
    if (this._MdButton_17_3.ngDoCheck(this,this._el_17,throwOnChange)) { this.compView_17.markAsCheckOnce(); }
    this._vc_8.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdOption_6_0.dirty) {
          this._query_MdOption_6_0.reset([this._vc_8.mapNestedViews(View_AIDetailComponent2,(nestedView:View_AIDetailComponent2):any => {
            return [nestedView._MdOption_0_3.context];
        })]);
        this._MdSelect_6_3.context.options = this._query_MdOption_6_0;
        this._query_MdOption_6_0.notifyOnChanges();
      }
      if (this._query_MdHint_11_1.dirty) {
        this._query_MdHint_11_1.reset(([] as any[]));
        this._MdInput_11_3.context._hintChildren = this._query_MdHint_11_1;
        this._query_MdHint_11_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._MdSelect_6_3.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._MdInput_11_3.context.ngAfterContentInit(); }
    }
    this._MdSelect_6_3.checkHost(this,this.compView_6,this._el_6,throwOnChange);
    this._MdInput_11_3.checkHost(this,this.compView_11,this._el_11,throwOnChange);
    this._NgControlStatus_11_7.checkHost(this,this.compView_11,this._el_11,throwOnChange);
    this._MdButton_14_3.checkHost(this,this.compView_14,this._el_14,throwOnChange);
    this._MdButton_17_3.checkHost(this,this.compView_17,this._el_17,throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
    this.compView_6.internalDetectChanges(throwOnChange);
    this.compView_11.internalDetectChanges(throwOnChange);
    this.compView_14.internalDetectChanges(throwOnChange);
    this.compView_17.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_8.destroyNestedViews();
    this.compView_2.destroy();
    this.compView_6.destroy();
    this.compView_11.destroy();
    this.compView_14.destroy();
    this.compView_17.destroy();
    this._MdSelect_6_3.ngOnDestroy();
    this._MdInput_11_3.ngOnDestroy();
    this._NgModel_11_5.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 2) && (ngContentIndex == 0))) {
      cb(this._text_3,ctx);
      cb(this._el_4,ctx);
      cb(this._text_20,ctx);
    }
    if (((nodeIndex == 6) && (ngContentIndex == 0))) {
      cb(this._text_7,ctx);
      cb(this._vc_8.nativeElement,ctx);
      this._vc_8.visitNestedViewRootNodes(cb,ctx);
      cb(this._text_9,ctx);
    }
    if (((nodeIndex == 11) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 11) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 11) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 11) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 14) && (ngContentIndex == 0))) { cb(this._text_15,ctx); }
    if (((nodeIndex == 17) && (ngContentIndex == 0))) { cb(this._text_18,ctx); }
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 8)) { return new View_AIDetailComponent2(this.viewUtils,this,8,this._anchor_8,this._vc_8); }
    return (null as any);
  }
  handleEvent_6(eventName:string,$event:any):boolean {
    this.compView_6.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdSelect_6_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_11(eventName:string,$event:any):boolean {
    this.compView_11.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInput_11_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.nHidden = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_14(eventName:string,$event:any):boolean {
    this.compView_14.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_14_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.ai.implant()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_17(eventName:string,$event:any):boolean {
    this.compView_17.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_17_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.ai.save()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_AIDetailComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_AIDetailComponent,{});
export class View_AIDetailComponent0 extends import2.AppView<import0.AIDetailComponent> {
  _anchor_0:any;
  /*private*/ _vc_0:import11.ViewContainer;
  _TemplateRef_0_5:any;
  _NgIf_0_6:import34.Wrapper_NgIf;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AIDetailComponent0,renderType_AIDetailComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_0 = new import11.ViewContainer(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import28.TemplateRef_(this,0,this._anchor_0);
    this._NgIf_0_6 = new import34.Wrapper_NgIf(this._vc_0.vcRef,this._TemplateRef_0_5);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [this._anchor_0]),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import28.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import35.NgIf) && (0 === requestNodeIndex))) { return this._NgIf_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.ai;
    this._NgIf_0_6.check_ngIf(currVal_0_0_0,throwOnChange,false);
    this._NgIf_0_6.ngDoCheck(this,this._anchor_0,throwOnChange);
    this._vc_0.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 0)) { return new View_AIDetailComponent1(this.viewUtils,this,0,this._anchor_0,this._vc_0); }
    return (null as any);
  }
}