/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../app/music-app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../app/services/db.service';
import * as import9 from '@angular/core/src/linker/view_container';
import * as import10 from '@angular/material/button-toggle/button-toggle';
import * as import11 from '../node_modules/@angular/material/button-toggle/button-toggle.ngfactory';
import * as import12 from '../node_modules/@angular/material/tooltip/tooltip.ngfactory';
import * as import13 from '@angular/material/icon/icon';
import * as import14 from '../node_modules/@angular/material/icon/icon.ngfactory';
import * as import15 from '@angular/material/core/coordination/unique-selection-dispatcher';
import * as import16 from '@angular/material/core/overlay/overlay';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/core/src/zone/ng_zone';
import * as import19 from '@angular/material/core/rtl/dir';
import * as import20 from '@angular/material/icon/icon-registry';
import * as import21 from '@angular/material/tooltip/tooltip';
import * as import22 from '@angular/material/button/button';
import * as import23 from '../node_modules/@angular/material/button/button.ngfactory';
import * as import24 from '@angular/core/src/linker/query_list';
import * as import25 from '../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import26 from '../../app/music/music.component';
import * as import27 from './music/music.component.ngfactory';
import * as import28 from '@angular/core/src/change_detection/change_detection_util';
import * as import29 from '@angular/core/src/linker/template_ref';
import * as import30 from '@angular/common/src/directives/ng_if';
export class Wrapper_MusicAppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.MusicAppComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.MusicAppComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_MusicAppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_MusicAppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.MusicAppComponent>;
  _MusicAppComponent_0_3:Wrapper_MusicAppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MusicAppComponent_Host0,renderType_MusicAppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'musicApp',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_MusicAppComponent0(this.viewUtils,this,0,this._el_0);
    this._MusicAppComponent_0_3 = new Wrapper_MusicAppComponent(this.injectorGet(import8.DBService,this.parentIndex));
    this.compView_0.create(this._MusicAppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._MusicAppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MusicAppComponent) && (0 === requestNodeIndex))) { return this._MusicAppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MusicAppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const MusicAppComponentNgFactory:import7.ComponentFactory<import0.MusicAppComponent> = new import7.ComponentFactory<import0.MusicAppComponent>('musicApp',View_MusicAppComponent_Host0,import0.MusicAppComponent);
const styles_MusicAppComponent:any[] = ([] as any[]);
class View_MusicAppComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _vc_0:import9.ViewContainer;
  compView_0:import1.AppView<import10.MdButtonToggle>;
  _MdButtonToggle_0_5:import11.Wrapper_MdButtonToggle;
  _MdTooltip_0_6:import12.Wrapper_MdTooltip;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import13.MdIcon>;
  _MdIcon_2_3:import14.Wrapper_MdIcon;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_MusicAppComponent1,renderType_MusicAppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'md-button-toggle',new import3.InlineArray4(4,'md-raised-button','','md-tooltip','pause/resume'),(null as any));
    this._vc_0 = new import9.ViewContainer(0,(null as any),this,this._el_0);
    this.compView_0 = new import11.View_MdButtonToggle0(this.viewUtils,this,0,this._el_0);
    this._MdButtonToggle_0_5 = new import11.Wrapper_MdButtonToggle(this.parentView.parentView.injectorGet(import10.MdButtonToggleGroup,this.parentView.parentIndex,(null as any)),this.parentView.parentView.injectorGet(import10.MdButtonToggleGroupMultiple,this.parentView.parentIndex,(null as any)),this.parentView.parentView.injectorGet(import15.UniqueSelectionDispatcher,this.parentView.parentIndex),this.renderer);
    this._MdTooltip_0_6 = new import12.Wrapper_MdTooltip(this.parentView.parentView.injectorGet(import16.Overlay,this.parentView.parentIndex),new import17.ElementRef(this._el_0),this._vc_0.vcRef,this.parentView.parentView.injectorGet(import18.NgZone,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import19.Dir,this.parentView.parentIndex,(null as any)));
    this._text_1 = this.renderer.createText((null as any),'\n                         ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,(null as any),'md-icon',new import3.InlineArray2(2,'role','img'),(null as any));
    this.compView_2 = new import14.View_MdIcon0(this.viewUtils,this,2,this._el_2);
    this._MdIcon_2_3 = new import14.Wrapper_MdIcon(new import17.ElementRef(this._el_2),this.renderer,this.parentView.parentView.injectorGet(import20.MdIconRegistry,this.parentView.parentIndex));
    this._text_3 = this.renderer.createText((null as any),'pause',(null as any));
    this.compView_2.create(this._MdIcon_2_3.context);
    this._text_4 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this.compView_0.create(this._MdButtonToggle_0_5.context);
    this._el_5 = this.renderer.createTemplateAnchor((null as any),(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray16(10,'click',(null as any),'longpress',(null as any),'touchend',(null as any),'mouseenter',(null as any),'mouseleave',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_5,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.MdIcon) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MdIcon_2_3.context; }
    if (((token === import10.MdButtonToggle) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._MdButtonToggle_0_5.context; }
    if (((token === import21.MdTooltip) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._MdTooltip_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MdButtonToggle_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_1_0:any = 'pause/resume';
    this._MdTooltip_0_6.check__deprecatedMessage(currVal_0_1_0,throwOnChange,false);
    this._MdTooltip_0_6.ngDoCheck(this,this._el_0,throwOnChange);
    if (this._MdIcon_2_3.ngDoCheck(this,this._el_2,throwOnChange)) { this.compView_2.markAsCheckOnce(); }
    this._vc_0.detectChangesInNestedViews(throwOnChange);
    this._MdButtonToggle_0_5.checkHost(this,this.compView_0,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { this._MdIcon_2_3.context.ngAfterViewChecked(); }
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
    this.compView_0.destroy();
    this.compView_2.destroy();
    this._MdButtonToggle_0_5.ngOnDestroy();
    this._MdTooltip_0_6.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._vc_0.nativeElement,ctx);
    this._vc_0.visitNestedViewRootNodes(cb,ctx);
    cb(this._el_5,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) {
      cb(this._text_1,ctx);
      cb(this._el_2,ctx);
      cb(this._text_4,ctx);
    }
    if (((nodeIndex == 2) && (ngContentIndex == 0))) { cb(this._text_3,ctx); }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdTooltip_0_6.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.pause()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_MusicAppComponent2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _vc_0:import9.ViewContainer;
  compView_0:import1.AppView<import22.MdButton>;
  _MdButton_0_5:import23.Wrapper_MdButton;
  _MdTooltip_0_6:import12.Wrapper_MdTooltip;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import13.MdIcon>;
  _MdIcon_2_3:import14.Wrapper_MdIcon;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_MusicAppComponent2,renderType_MusicAppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray8(6,'md-raised-button','','md-tooltip','START RECORDING','style','color:#FF0000;'),(null as any));
    this._vc_0 = new import9.ViewContainer(0,(null as any),this,this._el_0);
    this.compView_0 = new import23.View_MdButton0(this.viewUtils,this,0,this._el_0);
    this._MdButton_0_5 = new import23.Wrapper_MdButton(new import17.ElementRef(this._el_0),this.renderer);
    this._MdTooltip_0_6 = new import12.Wrapper_MdTooltip(this.parentView.parentView.injectorGet(import16.Overlay,this.parentView.parentIndex),new import17.ElementRef(this._el_0),this._vc_0.vcRef,this.parentView.parentView.injectorGet(import18.NgZone,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import19.Dir,this.parentView.parentIndex,(null as any)));
    this._text_1 = this.renderer.createText((null as any),'     \n                          ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,(null as any),'md-icon',new import3.InlineArray2(2,'role','img'),(null as any));
    this.compView_2 = new import14.View_MdIcon0(this.viewUtils,this,2,this._el_2);
    this._MdIcon_2_3 = new import14.Wrapper_MdIcon(new import17.ElementRef(this._el_2),this.renderer,this.parentView.parentView.injectorGet(import20.MdIconRegistry,this.parentView.parentIndex));
    this._text_3 = this.renderer.createText((null as any),'play_circle_filled',(null as any));
    this.compView_2.create(this._MdIcon_2_3.context);
    this._text_4 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this.compView_0.create(this._MdButton_0_5.context);
    this._el_5 = this.renderer.createTemplateAnchor((null as any),(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray16(16,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any),'longpress',(null as any),'touchend',(null as any),'mouseenter',(null as any),'mouseleave',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_5,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.MdIcon) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MdIcon_2_3.context; }
    if (((token === import22.MdButton) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._MdButton_0_5.context; }
    if (((token === import21.MdTooltip) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._MdTooltip_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._MdButton_0_5.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    const currVal_0_1_0:any = 'START RECORDING';
    this._MdTooltip_0_6.check__deprecatedMessage(currVal_0_1_0,throwOnChange,false);
    this._MdTooltip_0_6.ngDoCheck(this,this._el_0,throwOnChange);
    if (this._MdIcon_2_3.ngDoCheck(this,this._el_2,throwOnChange)) { this.compView_2.markAsCheckOnce(); }
    this._vc_0.detectChangesInNestedViews(throwOnChange);
    this._MdButton_0_5.checkHost(this,this.compView_0,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { this._MdIcon_2_3.context.ngAfterViewChecked(); }
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
    this.compView_0.destroy();
    this.compView_2.destroy();
    this._MdTooltip_0_6.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._vc_0.nativeElement,ctx);
    this._vc_0.visitNestedViewRootNodes(cb,ctx);
    cb(this._el_5,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) {
      cb(this._text_1,ctx);
      cb(this._el_2,ctx);
      cb(this._text_4,ctx);
    }
    if (((nodeIndex == 2) && (ngContentIndex == 0))) { cb(this._text_3,ctx); }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.compView_0.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_0_5.handleEvent(eventName,$event) && result);
    result = (this._MdTooltip_0_6.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.record()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_MusicAppComponent3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _vc_0:import9.ViewContainer;
  compView_0:import1.AppView<import22.MdButton>;
  _MdButton_0_5:import23.Wrapper_MdButton;
  _MdTooltip_0_6:import12.Wrapper_MdTooltip;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import13.MdIcon>;
  _MdIcon_2_3:import14.Wrapper_MdIcon;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_MusicAppComponent3,renderType_MusicAppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray8(6,'md-raised-button','','md-tooltip','STOP RECORDING','style','color:#FFFFFF;background-color:#FF0000;'),(null as any));
    this._vc_0 = new import9.ViewContainer(0,(null as any),this,this._el_0);
    this.compView_0 = new import23.View_MdButton0(this.viewUtils,this,0,this._el_0);
    this._MdButton_0_5 = new import23.Wrapper_MdButton(new import17.ElementRef(this._el_0),this.renderer);
    this._MdTooltip_0_6 = new import12.Wrapper_MdTooltip(this.parentView.parentView.injectorGet(import16.Overlay,this.parentView.parentIndex),new import17.ElementRef(this._el_0),this._vc_0.vcRef,this.parentView.parentView.injectorGet(import18.NgZone,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import19.Dir,this.parentView.parentIndex,(null as any)));
    this._text_1 = this.renderer.createText((null as any),'     \n                          ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,(null as any),'md-icon',new import3.InlineArray2(2,'role','img'),(null as any));
    this.compView_2 = new import14.View_MdIcon0(this.viewUtils,this,2,this._el_2);
    this._MdIcon_2_3 = new import14.Wrapper_MdIcon(new import17.ElementRef(this._el_2),this.renderer,this.parentView.parentView.injectorGet(import20.MdIconRegistry,this.parentView.parentIndex));
    this._text_3 = this.renderer.createText((null as any),'play_circle_filled',(null as any));
    this.compView_2.create(this._MdIcon_2_3.context);
    this._text_4 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this.compView_0.create(this._MdButton_0_5.context);
    this._el_5 = this.renderer.createTemplateAnchor((null as any),(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray16(16,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any),'longpress',(null as any),'touchend',(null as any),'mouseenter',(null as any),'mouseleave',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_5,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.MdIcon) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MdIcon_2_3.context; }
    if (((token === import22.MdButton) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._MdButton_0_5.context; }
    if (((token === import21.MdTooltip) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._MdTooltip_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._MdButton_0_5.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    const currVal_0_1_0:any = 'STOP RECORDING';
    this._MdTooltip_0_6.check__deprecatedMessage(currVal_0_1_0,throwOnChange,false);
    this._MdTooltip_0_6.ngDoCheck(this,this._el_0,throwOnChange);
    if (this._MdIcon_2_3.ngDoCheck(this,this._el_2,throwOnChange)) { this.compView_2.markAsCheckOnce(); }
    this._vc_0.detectChangesInNestedViews(throwOnChange);
    this._MdButton_0_5.checkHost(this,this.compView_0,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { this._MdIcon_2_3.context.ngAfterViewChecked(); }
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
    this.compView_0.destroy();
    this.compView_2.destroy();
    this._MdTooltip_0_6.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._vc_0.nativeElement,ctx);
    this._vc_0.visitNestedViewRootNodes(cb,ctx);
    cb(this._el_5,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) {
      cb(this._text_1,ctx);
      cb(this._el_2,ctx);
      cb(this._text_4,ctx);
    }
    if (((nodeIndex == 2) && (ngContentIndex == 0))) { cb(this._text_3,ctx); }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.compView_0.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_0_5.handleEvent(eventName,$event) && result);
    result = (this._MdTooltip_0_6.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.record()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_MusicAppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_MusicAppComponent,{});
export class View_MusicAppComponent0 extends import1.AppView<import0.MusicAppComponent> {
  _viewQuery_MusicComponent_0:import24.QueryList<any>;
  _text_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  /*private*/ _vc_8:import9.ViewContainer;
  compView_8:import1.AppView<import22.MdButton>;
  _MdButton_8_5:import23.Wrapper_MdButton;
  _MdTooltip_8_6:import12.Wrapper_MdTooltip;
  _text_9:any;
  _el_10:any;
  compView_10:import1.AppView<import13.MdIcon>;
  _MdIcon_10_3:import14.Wrapper_MdIcon;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _anchor_14:any;
  /*private*/ _vc_14:import9.ViewContainer;
  _TemplateRef_14_5:any;
  _NgIf_14_6:import25.Wrapper_NgIf;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _vc_16:import9.ViewContainer;
  _TemplateRef_16_5:any;
  _NgIf_16_6:import25.Wrapper_NgIf;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _vc_18:import9.ViewContainer;
  _TemplateRef_18_5:any;
  _NgIf_18_6:import25.Wrapper_NgIf;
  _text_19:any;
  _el_20:any;
  /*private*/ _vc_20:import9.ViewContainer;
  compView_20:import1.AppView<import22.MdButton>;
  _MdButton_20_5:import23.Wrapper_MdButton;
  _MdTooltip_20_6:import12.Wrapper_MdTooltip;
  _text_21:any;
  _el_22:any;
  compView_22:import1.AppView<import13.MdIcon>;
  _MdIcon_22_3:import14.Wrapper_MdIcon;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  compView_30:import1.AppView<import26.MusicComponent>;
  _MusicComponent_30_3:import27.Wrapper_MusicComponent;
  _text_31:any;
  _text_32:any;
  /*private*/ _expr_57:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MusicAppComponent0,renderType_MusicAppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_57 = import28.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._viewQuery_MusicComponent_0 = new import24.QueryList<any>();
    this._text_0 = this.renderer.createText(parentRenderNode,'\n\n		',(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n        \n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'style','width: 100%'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n  			',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','button-row'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','btn-group'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'button',new import3.InlineArray2(2,'md-raised-button',''),(null as any));
    this._vc_8 = new import9.ViewContainer(8,6,this,this._el_8);
    this.compView_8 = new import23.View_MdButton0(this.viewUtils,this,8,this._el_8);
    this._MdButton_8_5 = new import23.Wrapper_MdButton(new import17.ElementRef(this._el_8),this.renderer);
    this._MdTooltip_8_6 = new import12.Wrapper_MdTooltip(this.parentView.injectorGet(import16.Overlay,this.parentIndex),new import17.ElementRef(this._el_8),this._vc_8.vcRef,this.parentView.injectorGet(import18.NgZone,this.parentIndex),this.parentView.injectorGet(import19.Dir,this.parentIndex,(null as any)));
    this._text_9 = this.renderer.createText((null as any),'     \n                          ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,(null as any),'md-icon',new import3.InlineArray2(2,'role','img'),(null as any));
    this.compView_10 = new import14.View_MdIcon0(this.viewUtils,this,10,this._el_10);
    this._MdIcon_10_3 = new import14.Wrapper_MdIcon(new import17.ElementRef(this._el_10),this.renderer,this.parentView.injectorGet(import20.MdIconRegistry,this.parentIndex));
    this._text_11 = this.renderer.createText((null as any),'',(null as any));
    this.compView_10.create(this._MdIcon_10_3.context);
    this._text_12 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this.compView_8.create(this._MdButton_8_5.context);
    this._text_13 = this.renderer.createText(this._el_6,'\n                    \n                    ',(null as any));
    this._anchor_14 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._vc_14 = new import9.ViewContainer(14,6,this,this._anchor_14);
    this._TemplateRef_14_5 = new import29.TemplateRef_(this,14,this._anchor_14);
    this._NgIf_14_6 = new import25.Wrapper_NgIf(this._vc_14.vcRef,this._TemplateRef_14_5);
    this._text_15 = this.renderer.createText(this._el_6,'\n                     \n                    ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._vc_16 = new import9.ViewContainer(16,6,this,this._anchor_16);
    this._TemplateRef_16_5 = new import29.TemplateRef_(this,16,this._anchor_16);
    this._NgIf_16_6 = new import25.Wrapper_NgIf(this._vc_16.vcRef,this._TemplateRef_16_5);
    this._text_17 = this.renderer.createText(this._el_6,'\n                    \n                     ',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._vc_18 = new import9.ViewContainer(18,6,this,this._anchor_18);
    this._TemplateRef_18_5 = new import29.TemplateRef_(this,18,this._anchor_18);
    this._NgIf_18_6 = new import25.Wrapper_NgIf(this._vc_18.vcRef,this._TemplateRef_18_5);
    this._text_19 = this.renderer.createText(this._el_6,'\n                    \n                \n                    ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_6,'button',new import3.InlineArray8(6,'md-raised-button','','md-tooltip','SAVE','style','float: right'),(null as any));
    this._vc_20 = new import9.ViewContainer(20,6,this,this._el_20);
    this.compView_20 = new import23.View_MdButton0(this.viewUtils,this,20,this._el_20);
    this._MdButton_20_5 = new import23.Wrapper_MdButton(new import17.ElementRef(this._el_20),this.renderer);
    this._MdTooltip_20_6 = new import12.Wrapper_MdTooltip(this.parentView.injectorGet(import16.Overlay,this.parentIndex),new import17.ElementRef(this._el_20),this._vc_20.vcRef,this.parentView.injectorGet(import18.NgZone,this.parentIndex),this.parentView.injectorGet(import19.Dir,this.parentIndex,(null as any)));
    this._text_21 = this.renderer.createText((null as any),'\n                       ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,(null as any),'md-icon',new import3.InlineArray2(2,'role','img'),(null as any));
    this.compView_22 = new import14.View_MdIcon0(this.viewUtils,this,22,this._el_22);
    this._MdIcon_22_3 = new import14.Wrapper_MdIcon(new import17.ElementRef(this._el_22),this.renderer,this.parentView.injectorGet(import20.MdIconRegistry,this.parentIndex));
    this._text_23 = this.renderer.createText((null as any),'save',(null as any));
    this.compView_22.create(this._MdIcon_22_3.context);
    this._text_24 = this.renderer.createText((null as any),' \n                    ',(null as any));
    this.compView_20.create(this._MdButton_20_5.context);
    this._text_25 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._text_26 = this.renderer.createText(this._el_4,'\n         	',(null as any));
    this._text_27 = this.renderer.createText(this._el_2,'\n     	',(null as any));
    this._text_28 = this.renderer.createText(parentRenderNode,'\n\n     \n     	',(null as any));
    this._text_29 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,parentRenderNode,'music',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_30 = new import27.View_MusicComponent0(this.viewUtils,this,30,this._el_30);
    this._MusicComponent_30_3 = new import27.Wrapper_MusicComponent(this.parentView.injectorGet(import8.DBService,this.parentIndex));
    this._text_31 = this.renderer.createText((null as any),' ',(null as any));
    this.compView_30.create(this._MusicComponent_30_3.context);
    this._text_32 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_8,new import3.InlineArray16(16,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any),'longpress',(null as any),'touchend',(null as any),'mouseenter',(null as any),'mouseleave',(null as any)),this.eventHandler(this.handleEvent_8));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_20,new import3.InlineArray16(16,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any),'longpress',(null as any),'touchend',(null as any),'mouseenter',(null as any),'mouseleave',(null as any)),this.eventHandler(this.handleEvent_20));
    this._viewQuery_MusicComponent_0.reset([this._MusicComponent_30_3.context]);
    this.context.music = this._viewQuery_MusicComponent_0.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._anchor_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.MdIcon) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._MdIcon_10_3.context; }
    if (((token === import22.MdButton) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._MdButton_8_5.context; }
    if (((token === import21.MdTooltip) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._MdTooltip_8_6.context; }
    if (((token === import29.TemplateRef) && (14 === requestNodeIndex))) { return this._TemplateRef_14_5; }
    if (((token === import30.NgIf) && (14 === requestNodeIndex))) { return this._NgIf_14_6.context; }
    if (((token === import29.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import30.NgIf) && (16 === requestNodeIndex))) { return this._NgIf_16_6.context; }
    if (((token === import29.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import30.NgIf) && (18 === requestNodeIndex))) { return this._NgIf_18_6.context; }
    if (((token === import13.MdIcon) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._MdIcon_22_3.context; }
    if (((token === import22.MdButton) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._MdButton_20_5.context; }
    if (((token === import21.MdTooltip) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._MdTooltip_20_6.context; }
    if (((token === import26.MusicComponent) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._MusicComponent_30_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._MdButton_8_5.ngDoCheck(this,this._el_8,throwOnChange)) { this.compView_8.markAsCheckOnce(); }
    const currVal_8_1_0:any = import3.inlineInterpolate(1,'',this.context.playstopTip,'');
    this._MdTooltip_8_6.check__deprecatedMessage(currVal_8_1_0,throwOnChange,false);
    this._MdTooltip_8_6.ngDoCheck(this,this._el_8,throwOnChange);
    if (this._MdIcon_10_3.ngDoCheck(this,this._el_10,throwOnChange)) { this.compView_10.markAsCheckOnce(); }
    const currVal_14_0_0:any = this.context.pauseable;
    this._NgIf_14_6.check_ngIf(currVal_14_0_0,throwOnChange,false);
    this._NgIf_14_6.ngDoCheck(this,this._anchor_14,throwOnChange);
    const currVal_16_0_0:boolean = !this.context.recording;
    this._NgIf_16_6.check_ngIf(currVal_16_0_0,throwOnChange,false);
    this._NgIf_16_6.ngDoCheck(this,this._anchor_16,throwOnChange);
    const currVal_18_0_0:any = this.context.recording;
    this._NgIf_18_6.check_ngIf(currVal_18_0_0,throwOnChange,false);
    this._NgIf_18_6.ngDoCheck(this,this._anchor_18,throwOnChange);
    if (this._MdButton_20_5.ngDoCheck(this,this._el_20,throwOnChange)) { this.compView_20.markAsCheckOnce(); }
    const currVal_20_1_0:any = 'SAVE';
    this._MdTooltip_20_6.check__deprecatedMessage(currVal_20_1_0,throwOnChange,false);
    this._MdTooltip_20_6.ngDoCheck(this,this._el_20,throwOnChange);
    if (this._MdIcon_22_3.ngDoCheck(this,this._el_22,throwOnChange)) { this.compView_22.markAsCheckOnce(); }
    this._MusicComponent_30_3.ngDoCheck(this,this._el_30,throwOnChange);
    this._vc_8.detectChangesInNestedViews(throwOnChange);
    this._vc_14.detectChangesInNestedViews(throwOnChange);
    this._vc_16.detectChangesInNestedViews(throwOnChange);
    this._vc_18.detectChangesInNestedViews(throwOnChange);
    this._vc_20.detectChangesInNestedViews(throwOnChange);
    this._MdButton_8_5.checkHost(this,this.compView_8,this._el_8,throwOnChange);
    const currVal_57:any = import3.inlineInterpolate(1,' ',this.context.play_stop_icon,' ');
    if (import3.checkBinding(throwOnChange,this._expr_57,currVal_57)) {
      this.renderer.setText(this._text_11,currVal_57);
      this._expr_57 = currVal_57;
    }
    this._MdButton_20_5.checkHost(this,this.compView_20,this._el_20,throwOnChange);
    this.compView_8.internalDetectChanges(throwOnChange);
    this.compView_10.internalDetectChanges(throwOnChange);
    this.compView_20.internalDetectChanges(throwOnChange);
    this.compView_22.internalDetectChanges(throwOnChange);
    this.compView_30.internalDetectChanges(throwOnChange);
    if (!throwOnChange) {
      this._MdIcon_10_3.context.ngAfterViewChecked();
      this._MdIcon_22_3.context.ngAfterViewChecked();
      if ((this.numberOfChecks === 0)) { this._MusicComponent_30_3.context.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._vc_8.destroyNestedViews();
    this._vc_14.destroyNestedViews();
    this._vc_16.destroyNestedViews();
    this._vc_18.destroyNestedViews();
    this._vc_20.destroyNestedViews();
    this.compView_8.destroy();
    this.compView_10.destroy();
    this.compView_20.destroy();
    this.compView_22.destroy();
    this.compView_30.destroy();
    this._MdTooltip_8_6.ngOnDestroy();
    this._MdTooltip_20_6.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 8) && (ngContentIndex == 0))) {
      cb(this._text_9,ctx);
      cb(this._el_10,ctx);
      cb(this._text_12,ctx);
    }
    if (((nodeIndex == 10) && (ngContentIndex == 0))) { cb(this._text_11,ctx); }
    if (((nodeIndex == 20) && (ngContentIndex == 0))) {
      cb(this._text_21,ctx);
      cb(this._el_22,ctx);
      cb(this._text_24,ctx);
    }
    if (((nodeIndex == 22) && (ngContentIndex == 0))) { cb(this._text_23,ctx); }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 14)) { return new View_MusicAppComponent1(this.viewUtils,this,14,this._anchor_14,this._vc_14); }
    if ((nodeIndex == 16)) { return new View_MusicAppComponent2(this.viewUtils,this,16,this._anchor_16,this._vc_16); }
    if ((nodeIndex == 18)) { return new View_MusicAppComponent3(this.viewUtils,this,18,this._anchor_18,this._vc_18); }
    return (null as any);
  }
  handleEvent_8(eventName:string,$event:any):boolean {
    this.compView_8.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_8_5.handleEvent(eventName,$event) && result);
    result = (this._MdTooltip_8_6.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.play()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_20(eventName:string,$event:any):boolean {
    this.compView_20.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_20_5.handleEvent(eventName,$event) && result);
    result = (this._MdTooltip_20_6.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.save()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}