const BYTE_MASK = 0x80;

const HIGHBIT_MASK = 0x7f;

// Masks

const SYSEX_EVENT_MASK = 0xf0;

const NOTE_ON_MASK = 0x90;

const NOTE_OFF_MASK = 0x80;

const PROGRAM_MASK = 0xc0;

const CHANNEL_MASK = 0xd0;

const CONTROL_MASK = 0xb0;

const META_EVENT = 0xff;

// Meta subtypes

const SEQUENCE_META_EVENT = 0x00;

const TEXT_META_EVENT = 0x01;

const COPYRIGHT_META_EVENT = 0x02;

const TRACK_NAME_META_EVENT = 0x03;

const INST_NAME_META_EVENT = 0x04;
const LYRIC_TEXT_META_EVENT = 0x05;

const MARKER_TEXT_META_EVENT = 0x06;

const CUE_POINT_META_EVENT = 0x07;

const CHANNEL_PREFIX_ASSIGNMENT_META_EVENT = 0x20;

const END_OF_TRACK_META_EVENT = 0x2f;
const TEMPO_META_EVENT = 0x51;

const SMPTE_OFFSET_META_EVENT = 0x54;

const TIME_SIG_META_EVENT = 0x58;

const KEY_SIGNATURE_META_EVENT = 0x59;

const SEQUENCER_SPECIFIC_META_EVENT = 0x7f;


export const Midi = {
    BANK_SELECT_CC: 0,
    BANK_LSB_CC: 32,
    BYTE_MASK: BYTE_MASK,
    HIGHBIT_MASK: HIGHBIT_MASK,
    SYSEX_EVENT_MASK: SYSEX_EVENT_MASK,
    NOTE_ON_MASK: NOTE_ON_MASK,
    NOTE_OFF_MASK: NOTE_OFF_MASK,
    PROGRAM_MASK: PROGRAM_MASK,
    CHANNEL_MASK: CHANNEL_MASK,
    CONTROL_MASK: CONTROL_MASK,
    META_EVENT: META_EVENT,
    SEQUENCE_META_EVENT: SEQUENCE_META_EVENT,
    TEXT_META_EVENT: TEXT_META_EVENT,
    COPYRIGHT_META_EVENT: COPYRIGHT_META_EVENT,
    TRACK_NAME_META_EVENT: TRACK_NAME_META_EVENT,
    INST_NAME_META_EVENT: INST_NAME_META_EVENT,
    LYRIC_TEXT_META_EVENT: LYRIC_TEXT_META_EVENT,
    MARKER_TEXT_META_EVENT: MARKER_TEXT_META_EVENT,
    CUE_POINT_META_EVENT: CUE_POINT_META_EVENT,
    CHANNEL_PREFIX_ASSIGNMENT_META_EVENT: CHANNEL_PREFIX_ASSIGNMENT_META_EVENT,
    END_OF_TRACK_META_EVENT: END_OF_TRACK_META_EVENT,
    TEMPO_META_EVENT: TEMPO_META_EVENT,
    SMPTE_OFFSET_META_EVENT: SMPTE_OFFSET_META_EVENT,
    TIME_SIG_META_EVENT: TIME_SIG_META_EVENT,
    KEY_SIGNATURE_META_EVENT: KEY_SIGNATURE_META_EVENT,
    SEQUENCER_SPECIFIC_META_EVENT: SEQUENCER_SPECIFIC_META_EVENT
};



export class MidiEvent {
    constructor(public stamp: number, public effect: Array<number>) {

    }
}

export class MidiLane extends Array<MidiEvent> {


    chan: number;
    prog: string;

    constructor(prog?: string, chan?: number) {
        super();
        this.chan = chan;
        this.prog = prog;
    }
}
