/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/music/music.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../app/services/db.service';
import * as import9 from '../../../app/music/player-detail.component';
import * as import10 from './player-detail.component.ngfactory';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '@angular/material/card/card';
import * as import13 from '../../node_modules/@angular/material/card/card.ngfactory';
import * as import14 from '@angular/material/button/button';
import * as import15 from '../../node_modules/@angular/material/button/button.ngfactory';
import * as import16 from '@angular/material/icon/icon';
import * as import17 from '../../node_modules/@angular/material/icon/icon.ngfactory';
import * as import18 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from '@angular/material/icon/icon-registry';
import * as import21 from '@angular/core/src/linker/template_ref';
import * as import22 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import23 from '@angular/common/src/directives/ng_for';
export class Wrapper_MusicComponent {
  /*private*/ _eventHandler:Function;
  context:import0.MusicComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.MusicComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_MusicComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_MusicComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.MusicComponent>;
  _MusicComponent_0_3:Wrapper_MusicComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MusicComponent_Host0,renderType_MusicComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'music',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_MusicComponent0(this.viewUtils,this,0,this._el_0);
    this._MusicComponent_0_3 = new Wrapper_MusicComponent(this.injectorGet(import8.DBService,this.parentIndex));
    this.compView_0.create(this._MusicComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._MusicComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MusicComponent) && (0 === requestNodeIndex))) { return this._MusicComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MusicComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._MusicComponent_0_3.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const MusicComponentNgFactory:import7.ComponentFactory<import0.MusicComponent> = new import7.ComponentFactory<import0.MusicComponent>('music',View_MusicComponent_Host0,import0.MusicComponent);
const styles_MusicComponent:any[] = ([] as any[]);
class View_MusicComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import9.PlayerDetailComponent>;
  _PlayerDetailComponent_2_3:import10.Wrapper_PlayerDetailComponent;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_MusicComponent1,renderType_MusicComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n               ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'player-detail',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import10.View_PlayerDetailComponent0(this.viewUtils,this,2,this._el_2);
    this._PlayerDetailComponent_2_3 = new import10.Wrapper_PlayerDetailComponent();
    this._text_3 = this.renderer.createText((null as any),' ',(null as any));
    this.compView_2.create(this._PlayerDetailComponent_2_3.context);
    this._text_4 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.PlayerDetailComponent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._PlayerDetailComponent_2_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.context.$implicit;
    this._PlayerDetailComponent_2_3.check_player(currVal_2_0_0,throwOnChange,false);
    this._PlayerDetailComponent_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_2.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
var renderType_MusicComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_MusicComponent,{});
export class View_MusicComponent0 extends import1.AppView<import0.MusicComponent> {
  _text_0:any;
  _el_1:any;
  compView_1:import1.AppView<import12.MdCard>;
  _MdCard_1_3:import13.Wrapper_MdCard;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _MdCardTitle_5_3:import13.Wrapper_MdCardTitle;
  _text_6:any;
  _el_7:any;
  compView_7:import1.AppView<import14.MdButton>;
  _MdButton_7_3:import15.Wrapper_MdButton;
  _el_8:any;
  compView_8:import1.AppView<import16.MdIcon>;
  _MdIcon_8_3:import17.Wrapper_MdIcon;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _MdCardContent_13_3:import13.Wrapper_MdCardContent;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _vc_15:import11.ViewContainer;
  _TemplateRef_15_5:any;
  _NgFor_15_6:import18.Wrapper_NgFor;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MusicComponent0,renderType_MusicComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n       ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'md-card',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_1 = new import13.View_MdCard0(this.viewUtils,this,1,this._el_1);
    this._MdCard_1_3 = new import13.Wrapper_MdCard();
    this._text_2 = this.renderer.createText((null as any),'             \n            ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'style','width: 100%'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n            ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'md-card-title',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardTitle_5_3 = new import13.Wrapper_MdCardTitle();
    this._text_6 = this.renderer.createText(this._el_5,'\n              ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'button',new import3.InlineArray2(2,'md-mini-fab',''),(null as any));
    this.compView_7 = new import15.View_MdButton0(this.viewUtils,this,7,this._el_7);
    this._MdButton_7_3 = new import15.Wrapper_MdButton(new import19.ElementRef(this._el_7),this.renderer);
    this._el_8 = import3.createRenderElement(this.renderer,(null as any),'md-icon',new import3.InlineArray2(2,'role','img'),(null as any));
    this.compView_8 = new import17.View_MdIcon0(this.viewUtils,this,8,this._el_8);
    this._MdIcon_8_3 = new import17.Wrapper_MdIcon(new import19.ElementRef(this._el_8),this.renderer,this.parentView.injectorGet(import20.MdIconRegistry,this.parentIndex));
    this._text_9 = this.renderer.createText((null as any),'add',(null as any));
    this.compView_8.create(this._MdIcon_8_3.context);
    this.compView_7.create(this._MdButton_7_3.context);
    this._el_10 = import3.createRenderElement(this.renderer,this._el_5,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._text_12 = this.renderer.createText(this._el_3,'\n            ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_3,'md-card-content',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardContent_13_3 = new import13.Wrapper_MdCardContent();
    this._text_14 = this.renderer.createText(this._el_13,'\n\n            ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor(this._el_13,(null as any));
    this._vc_15 = new import11.ViewContainer(15,13,this,this._anchor_15);
    this._TemplateRef_15_5 = new import21.TemplateRef_(this,15,this._anchor_15);
    this._NgFor_15_6 = new import18.Wrapper_NgFor(this._vc_15.vcRef,this._TemplateRef_15_5,this.parentView.injectorGet(import22.IterableDiffers,this.parentIndex),this.ref);
    this._text_16 = this.renderer.createText(this._el_13,'\n 	       	',(null as any));
    this._text_17 = this.renderer.createText(this._el_3,'        \n        	',(null as any));
    this._text_18 = this.renderer.createText((null as any),'    \n       ',(null as any));
    this.compView_1.create(this._MdCard_1_3.context);
    this._text_19 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_7,new import3.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_7));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._text_19
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.MdIcon) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._MdIcon_8_3.context; }
    if (((token === import14.MdButton) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._MdButton_7_3.context; }
    if (((token === import12.MdCardTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._MdCardTitle_5_3.context; }
    if (((token === import21.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import23.NgFor) && (15 === requestNodeIndex))) { return this._NgFor_15_6.context; }
    if (((token === import12.MdCardContent) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._MdCardContent_13_3.context; }
    if (((token === import12.MdCard) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._MdCard_1_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._MdCard_1_3.ngDoCheck(this,this._el_1,throwOnChange)) { this.compView_1.markAsCheckOnce(); }
    this._MdCardTitle_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    if (this._MdButton_7_3.ngDoCheck(this,this._el_7,throwOnChange)) { this.compView_7.markAsCheckOnce(); }
    if (this._MdIcon_8_3.ngDoCheck(this,this._el_8,throwOnChange)) { this.compView_8.markAsCheckOnce(); }
    this._MdCardContent_13_3.ngDoCheck(this,this._el_13,throwOnChange);
    const currVal_15_0_0:any = this.context.players;
    this._NgFor_15_6.check_ngForOf(currVal_15_0_0,throwOnChange,false);
    this._NgFor_15_6.ngDoCheck(this,this._anchor_15,throwOnChange);
    this._vc_15.detectChangesInNestedViews(throwOnChange);
    this._MdButton_7_3.checkHost(this,this.compView_7,this._el_7,throwOnChange);
    this.compView_1.internalDetectChanges(throwOnChange);
    this.compView_7.internalDetectChanges(throwOnChange);
    this.compView_8.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { this._MdIcon_8_3.context.ngAfterViewChecked(); }
  }
  destroyInternal():void {
    this._vc_15.destroyNestedViews();
    this.compView_1.destroy();
    this.compView_7.destroy();
    this.compView_8.destroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 1) && (ngContentIndex == 0))) {
      cb(this._text_2,ctx);
      cb(this._el_3,ctx);
      cb(this._text_18,ctx);
    }
    if (((nodeIndex == 7) && (ngContentIndex == 0))) { cb(this._el_8,ctx); }
    if (((nodeIndex == 8) && (ngContentIndex == 0))) { cb(this._text_9,ctx); }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 15)) { return new View_MusicComponent1(this.viewUtils,this,15,this._anchor_15,this._vc_15); }
    return (null as any);
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.compView_7.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_7_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.addPlayer((undefined as any))) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}