/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/music/music.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../app/services/db.service';
import * as import9 from '@angular/material/menu/menu-item';
import * as import10 from '../../node_modules/@angular/material/menu/menu-item.ngfactory';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '@angular/core/src/change_detection/change_detection_util';
import * as import13 from '@angular/core/src/linker/element_ref';
import * as import14 from '../../../app/music/player-detail.component';
import * as import15 from './player-detail.component.ngfactory';
import * as import16 from '@angular/material/card/card';
import * as import17 from '../../node_modules/@angular/material/card/card.ngfactory';
import * as import18 from '@angular/material/button/button';
import * as import19 from '../../node_modules/@angular/material/button/button.ngfactory';
import * as import20 from '../../node_modules/@angular/material/menu/menu-trigger.ngfactory';
import * as import21 from '@angular/material/icon/icon';
import * as import22 from '../../node_modules/@angular/material/icon/icon.ngfactory';
import * as import23 from '@angular/material/menu/menu-directive';
import * as import24 from '../../node_modules/@angular/material/menu/menu-directive.ngfactory';
import * as import25 from '@angular/core/src/linker/query_list';
import * as import26 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import27 from '@angular/material/core/overlay/overlay';
import * as import28 from '@angular/material/core/rtl/dir';
import * as import29 from '@angular/material/icon/icon-registry';
import * as import30 from '@angular/core/src/linker/template_ref';
import * as import31 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import32 from '@angular/material/menu/menu-trigger';
import * as import33 from '@angular/common/src/directives/ng_for';
export class Wrapper_MusicComponent {
  /*private*/ _eventHandler:Function;
  context:import0.MusicComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.MusicComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_MusicComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_MusicComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.MusicComponent>;
  _MusicComponent_0_3:Wrapper_MusicComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MusicComponent_Host0,renderType_MusicComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'music',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_MusicComponent0(this.viewUtils,this,0,this._el_0);
    this._MusicComponent_0_3 = new Wrapper_MusicComponent(this.injectorGet(import8.DBService,this.parentIndex));
    this.compView_0.create(this._MusicComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._MusicComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MusicComponent) && (0 === requestNodeIndex))) { return this._MusicComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MusicComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._MusicComponent_0_3.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const MusicComponentNgFactory:import7.ComponentFactory<import0.MusicComponent> = new import7.ComponentFactory<import0.MusicComponent>('music',View_MusicComponent_Host0,import0.MusicComponent);
const styles_MusicComponent:any[] = ([] as any[]);
class View_MusicComponent1 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import9.MdMenuItem>;
  _MdMenuItem_0_3:import10.Wrapper_MdMenuItem;
  _text_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_MusicComponent1,renderType_MusicComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_4 = import12.UNINITIALIZED;
    this._expr_5 = import12.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray4(4,'md-menu-item','','role','menuitem'),(null as any));
    this.compView_0 = new import10.View_MdMenuItem0(this.viewUtils,this,0,this._el_0);
    this._MdMenuItem_0_3 = new import10.Wrapper_MdMenuItem(this.renderer,new import13.ElementRef(this._el_0));
    this._text_1 = this.renderer.createText((null as any),'',(null as any));
    this.compView_0.create(this._MdMenuItem_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.MdMenuItem) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._MdMenuItem_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MdMenuItem_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_4:any = this.parentView.context.playerType;
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_0,'value',currVal_4);
      this._expr_4 = currVal_4;
    }
    this._MdMenuItem_0_3.checkHost(this,this.compView_0,this._el_0,throwOnChange);
    const currVal_5:any = import3.inlineInterpolate(1,'\n                          ',this.context.$implicit,'\n                         ');
    if (import3.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_1,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<View_MusicComponent0>this.parentView)._query_MdMenuItem_13_0.setDirty();
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) { cb(this._text_1,ctx); }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.compView_0.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdMenuItem_0_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.addPlayerType(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_MusicComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import14.PlayerDetailComponent>;
  _PlayerDetailComponent_2_3:import15.Wrapper_PlayerDetailComponent;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_MusicComponent2,renderType_MusicComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n               ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'player-detail',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import15.View_PlayerDetailComponent0(this.viewUtils,this,2,this._el_2);
    this._PlayerDetailComponent_2_3 = new import15.Wrapper_PlayerDetailComponent();
    this._text_3 = this.renderer.createText((null as any),' ',(null as any));
    this.compView_2.create(this._PlayerDetailComponent_2_3.context);
    this._text_4 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'playerSelected',(null as any)),this.eventHandler(this.handleEvent_2));
    this._PlayerDetailComponent_2_3.subscribe(this,this.eventHandler(this.handleEvent_2),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.PlayerDetailComponent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._PlayerDetailComponent_2_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.context.$implicit;
    this._PlayerDetailComponent_2_3.check_player(currVal_2_0_0,throwOnChange,false);
    this._PlayerDetailComponent_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_2.destroy();
    this._PlayerDetailComponent_2_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'playerSelected')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.slectedPlayer = this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_MusicComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_MusicComponent,{});
export class View_MusicComponent0 extends import1.AppView<import0.MusicComponent> {
  _text_0:any;
  _el_1:any;
  compView_1:import1.AppView<import16.MdCard>;
  _MdCard_1_3:import17.Wrapper_MdCard;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  /*private*/ _vc_6:import11.ViewContainer;
  compView_6:import1.AppView<import18.MdButton>;
  _MdButton_6_5:import19.Wrapper_MdButton;
  _MdMenuTrigger_6_6:import20.Wrapper_MdMenuTrigger;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  compView_9:import1.AppView<import21.MdIcon>;
  _MdIcon_9_3:import22.Wrapper_MdIcon;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  compView_13:import1.AppView<import23.MdMenu>;
  _MdMenu_13_3:import24.Wrapper_MdMenu;
  _query_MdMenuItem_13_0:import25.QueryList<any>;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _vc_15:import11.ViewContainer;
  _TemplateRef_15_5:any;
  _NgFor_15_6:import26.Wrapper_NgFor;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _el_21:any;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _vc_23:import11.ViewContainer;
  _TemplateRef_23_5:any;
  _NgFor_23_6:import26.Wrapper_NgFor;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MusicComponent0,renderType_MusicComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n \n       ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'md-card',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_1 = new import17.View_MdCard0(this.viewUtils,this,1,this._el_1);
    this._MdCard_1_3 = new import17.Wrapper_MdCard();
    this._text_2 = this.renderer.createText((null as any),'             \n            ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'style','width: 100%'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n\n             ',(null as any));
    this._text_5 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_3,'button',new import3.InlineArray4(4,'aria-haspopup','true','md-mini-fab',''),(null as any));
    this._vc_6 = new import11.ViewContainer(6,3,this,this._el_6);
    this.compView_6 = new import19.View_MdButton0(this.viewUtils,this,6,this._el_6);
    this._MdButton_6_5 = new import19.Wrapper_MdButton(new import13.ElementRef(this._el_6),this.renderer);
    this._MdMenuTrigger_6_6 = new import20.Wrapper_MdMenuTrigger(this.parentView.injectorGet(import27.Overlay,this.parentIndex),new import13.ElementRef(this._el_6),this._vc_6.vcRef,this.renderer,this.parentView.injectorGet(import28.Dir,this.parentIndex,(null as any)));
    this._text_7 = this.renderer.createText((null as any),' ',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n                      ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,(null as any),'md-icon',new import3.InlineArray2(2,'role','img'),(null as any));
    this.compView_9 = new import22.View_MdIcon0(this.viewUtils,this,9,this._el_9);
    this._MdIcon_9_3 = new import22.Wrapper_MdIcon(new import13.ElementRef(this._el_9),this.renderer,this.parentView.injectorGet(import29.MdIconRegistry,this.parentIndex));
    this._text_10 = this.renderer.createText((null as any),'add',(null as any));
    this.compView_9.create(this._MdIcon_9_3.context);
    this._text_11 = this.renderer.createText((null as any),'\n                 ',(null as any));
    this.compView_6.create(this._MdButton_6_5.context);
    this._text_12 = this.renderer.createText(this._el_3,' \n                 ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_3,'md-menu',new import3.InlineArray2(2,'role','menu'),(null as any));
    this.compView_13 = new import24.View_MdMenu0(this.viewUtils,this,13,this._el_13);
    this._MdMenu_13_3 = new import24.Wrapper_MdMenu((null as any),(null as any));
    this._query_MdMenuItem_13_0 = new import25.QueryList<any>();
    this._text_14 = this.renderer.createText((null as any),'\n                         ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_15 = new import11.ViewContainer(15,13,this,this._anchor_15);
    this._TemplateRef_15_5 = new import30.TemplateRef_(this,15,this._anchor_15);
    this._NgFor_15_6 = new import26.Wrapper_NgFor(this._vc_15.vcRef,this._TemplateRef_15_5,this.parentView.injectorGet(import31.IterableDiffers,this.parentIndex),this.ref);
    this._text_16 = this.renderer.createText((null as any),'\n\n                ',(null as any));
    this.compView_13.create(this._MdMenu_13_3.context);
    this._text_17 = this.renderer.createText(this._el_3,'\n              \n            ',(null as any));
    this._text_18 = this.renderer.createText(this._el_3,'\n\n            ',(null as any));
    this._text_19 = this.renderer.createText(this._el_3,'\n            ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_3,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_3,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_22 = this.renderer.createText(this._el_3,'\n            ',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._vc_23 = new import11.ViewContainer(23,3,this,this._anchor_23);
    this._TemplateRef_23_5 = new import30.TemplateRef_(this,23,this._anchor_23);
    this._NgFor_23_6 = new import26.Wrapper_NgFor(this._vc_23.vcRef,this._TemplateRef_23_5,this.parentView.injectorGet(import31.IterableDiffers,this.parentIndex),this.ref);
    this._text_24 = this.renderer.createText(this._el_3,'\n 	       	',(null as any));
    this._text_25 = this.renderer.createText(this._el_3,'        \n        	',(null as any));
    this._text_26 = this.renderer.createText((null as any),'    \n       ',(null as any));
    this.compView_1.create(this._MdCard_1_3.context);
    this._text_27 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_6,new import3.InlineArray8(8,'mousedown',(null as any),'focus',(null as any),'blur',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_6));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._el_21,
      this._text_22,
      this._anchor_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.MdIcon) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._MdIcon_9_3.context; }
    if (((token === import18.MdButton) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._MdButton_6_5.context; }
    if (((token === import32.MdMenuTrigger) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._MdMenuTrigger_6_6.context; }
    if (((token === import30.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import33.NgFor) && (15 === requestNodeIndex))) { return this._NgFor_15_6.context; }
    if (((token === import23.MdMenu) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._MdMenu_13_3.context; }
    if (((token === import30.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import33.NgFor) && (23 === requestNodeIndex))) { return this._NgFor_23_6.context; }
    if (((token === import16.MdCard) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._MdCard_1_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._MdCard_1_3.ngDoCheck(this,this._el_1,throwOnChange)) { this.compView_1.markAsCheckOnce(); }
    if (this._MdButton_6_5.ngDoCheck(this,this._el_6,throwOnChange)) { this.compView_6.markAsCheckOnce(); }
    const currVal_6_1_0:any = this._MdMenu_13_3.context;
    this._MdMenuTrigger_6_6.check__deprecatedMenuTriggerFor(currVal_6_1_0,throwOnChange,false);
    this._MdMenuTrigger_6_6.ngDoCheck(this,this._el_6,throwOnChange);
    if (this._MdIcon_9_3.ngDoCheck(this,this._el_9,throwOnChange)) { this.compView_9.markAsCheckOnce(); }
    this._MdMenu_13_3.ngDoCheck(this,this._el_13,throwOnChange);
    const currVal_15_0_0:any = this.context.playerTypes;
    this._NgFor_15_6.check_ngForOf(currVal_15_0_0,throwOnChange,false);
    this._NgFor_15_6.ngDoCheck(this,this._anchor_15,throwOnChange);
    const currVal_23_0_0:any = this.context.players;
    this._NgFor_23_6.check_ngForOf(currVal_23_0_0,throwOnChange,false);
    this._NgFor_23_6.ngDoCheck(this,this._anchor_23,throwOnChange);
    this._vc_6.detectChangesInNestedViews(throwOnChange);
    this._vc_15.detectChangesInNestedViews(throwOnChange);
    this._vc_23.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdMenuItem_13_0.dirty) {
          this._query_MdMenuItem_13_0.reset([this._vc_15.mapNestedViews(View_MusicComponent1,(nestedView:View_MusicComponent1):any => {
            return [nestedView._MdMenuItem_0_3.context];
        })]);
        this._MdMenu_13_3.context.items = this._query_MdMenuItem_13_0;
        this._query_MdMenuItem_13_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._MdMenu_13_3.context.ngAfterContentInit(); }
    }
    this._MdButton_6_5.checkHost(this,this.compView_6,this._el_6,throwOnChange);
    this.compView_1.internalDetectChanges(throwOnChange);
    this.compView_6.internalDetectChanges(throwOnChange);
    this.compView_9.internalDetectChanges(throwOnChange);
    this.compView_13.internalDetectChanges(throwOnChange);
    if (!throwOnChange) {
      this._MdIcon_9_3.context.ngAfterViewChecked();
      if ((this.numberOfChecks === 0)) { this._MdMenuTrigger_6_6.context.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._vc_6.destroyNestedViews();
    this._vc_15.destroyNestedViews();
    this._vc_23.destroyNestedViews();
    this.compView_1.destroy();
    this.compView_6.destroy();
    this.compView_9.destroy();
    this.compView_13.destroy();
    this._MdMenuTrigger_6_6.ngOnDestroy();
    this._MdMenu_13_3.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 1) && (ngContentIndex == 0))) {
      cb(this._text_2,ctx);
      cb(this._el_3,ctx);
      cb(this._text_26,ctx);
    }
    if (((nodeIndex == 6) && (ngContentIndex == 0))) {
      cb(this._text_7,ctx);
      cb(this._text_8,ctx);
      cb(this._el_9,ctx);
      cb(this._text_11,ctx);
    }
    if (((nodeIndex == 9) && (ngContentIndex == 0))) { cb(this._text_10,ctx); }
    if (((nodeIndex == 13) && (ngContentIndex == 0))) {
      cb(this._text_14,ctx);
      cb(this._vc_15.nativeElement,ctx);
      this._vc_15.visitNestedViewRootNodes(cb,ctx);
      cb(this._text_16,ctx);
    }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 15)) { return new View_MusicComponent1(this.viewUtils,this,15,this._anchor_15,this._vc_15); }
    if ((nodeIndex == 23)) { return new View_MusicComponent2(this.viewUtils,this,23,this._anchor_23,this._vc_23); }
    return (null as any);
  }
  handleEvent_6(eventName:string,$event:any):boolean {
    this.compView_6.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_6_5.handleEvent(eventName,$event) && result);
    result = (this._MdMenuTrigger_6_6.handleEvent(eventName,$event) && result);
    return result;
  }
}