/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/music/ai-detail.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@angular/material/menu/menu-item';
import * as import10 from '../../node_modules/@angular/material/menu/menu-item.ngfactory';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '@angular/core/src/linker/element_ref';
import * as import13 from '@angular/material/card/card';
import * as import14 from '../../node_modules/@angular/material/card/card.ngfactory';
import * as import15 from '@angular/material/button/button';
import * as import16 from '../../node_modules/@angular/material/button/button.ngfactory';
import * as import17 from '../../node_modules/@angular/material/menu/menu-trigger.ngfactory';
import * as import18 from '@angular/material/menu/menu-directive';
import * as import19 from '../../node_modules/@angular/material/menu/menu-directive.ngfactory';
import * as import20 from '@angular/core/src/linker/query_list';
import * as import21 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import22 from '@angular/material/input/input';
import * as import23 from '../../node_modules/@angular/material/input/input.ngfactory';
import * as import24 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import25 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import26 from '@angular/material/icon/icon';
import * as import27 from '../../node_modules/@angular/material/icon/icon.ngfactory';
import * as import28 from '@angular/material/core/overlay/overlay';
import * as import29 from '@angular/material/core/rtl/dir';
import * as import30 from '@angular/core/src/linker/template_ref';
import * as import31 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import32 from '@angular/material/icon/icon-registry';
import * as import33 from '@angular/material/menu/menu-trigger';
import * as import34 from '@angular/common/src/directives/ng_for';
import * as import35 from '@angular/forms/src/directives/control_value_accessor';
import * as import36 from '@angular/forms/src/directives/ng_model';
import * as import37 from '@angular/forms/src/directives/ng_control';
import * as import38 from '@angular/forms/src/directives/ng_control_status';
import * as import39 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import40 from '@angular/common/src/directives/ng_if';
export class Wrapper_AIDetailComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AIDetailComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  constructor() {
    this._changed = false;
    this.context = new import0.AIDetailComponent();
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_ai(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.ai = currValue;
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AIDetailComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_AIDetailComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.AIDetailComponent>;
  _AIDetailComponent_0_3:Wrapper_AIDetailComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AIDetailComponent_Host0,renderType_AIDetailComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ai-detail',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AIDetailComponent0(this.viewUtils,this,0,this._el_0);
    this._AIDetailComponent_0_3 = new Wrapper_AIDetailComponent();
    this.compView_0.create(this._AIDetailComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._AIDetailComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AIDetailComponent) && (0 === requestNodeIndex))) { return this._AIDetailComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AIDetailComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AIDetailComponentNgFactory:import8.ComponentFactory<import0.AIDetailComponent> = new import8.ComponentFactory<import0.AIDetailComponent>('ai-detail',View_AIDetailComponent_Host0,import0.AIDetailComponent);
const styles_AIDetailComponent:any[] = ([] as any[]);
class View_AIDetailComponent2 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import9.MdMenuItem>;
  _MdMenuItem_0_3:import10.Wrapper_MdMenuItem;
  _text_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_AIDetailComponent2,renderType_AIDetailComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_4 = import1.UNINITIALIZED;
    this._expr_5 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray4(4,'md-menu-item','','role','menuitem'),(null as any));
    this.compView_0 = new import10.View_MdMenuItem0(this.viewUtils,this,0,this._el_0);
    this._MdMenuItem_0_3 = new import10.Wrapper_MdMenuItem(this.renderer,new import12.ElementRef(this._el_0));
    this._text_1 = this.renderer.createText((null as any),'',(null as any));
    this.compView_0.create(this._MdMenuItem_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.MdMenuItem) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._MdMenuItem_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MdMenuItem_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_4:any = this.parentView.parentView.context.playerType;
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_0,'value',currVal_4);
      this._expr_4 = currVal_4;
    }
    this._MdMenuItem_0_3.checkHost(this,this.compView_0,this._el_0,throwOnChange);
    const currVal_5:any = import3.inlineInterpolate(1,'\n                          ',this.context.$implicit,'\n                   ');
    if (import3.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_1,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<View_AIDetailComponent1>this.parentView)._query_MdMenuItem_10_0.setDirty();
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) { cb(this._text_1,ctx); }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.compView_0.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdMenuItem_0_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.parentView.parentView.context.aiType = this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_AIDetailComponent1 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import2.AppView<import13.MdCard>;
  _MdCard_2_3:import14.Wrapper_MdCard;
  _text_3:any;
  _el_4:any;
  _MdCardActions_4_3:import14.Wrapper_MdCardActions;
  _text_5:any;
  _el_6:any;
  /*private*/ _vc_6:import11.ViewContainer;
  compView_6:import2.AppView<import15.MdButton>;
  _MdButton_6_5:import16.Wrapper_MdButton;
  _MdMenuTrigger_6_6:import17.Wrapper_MdMenuTrigger;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  compView_10:import2.AppView<import18.MdMenu>;
  _MdMenu_10_3:import19.Wrapper_MdMenu;
  _query_MdMenuItem_10_0:import20.QueryList<any>;
  _text_11:any;
  _anchor_12:any;
  /*private*/ _vc_12:import11.ViewContainer;
  _TemplateRef_12_5:any;
  _NgFor_12_6:import21.Wrapper_NgFor;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  compView_15:import2.AppView<import22.MdInput>;
  _MdInput_15_3:import23.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_15_4:any[];
  _NgModel_15_5:import24.Wrapper_NgModel;
  _NgControl_15_6:any;
  _NgControlStatus_15_7:import25.Wrapper_NgControlStatus;
  _query_MdPlaceholder_15_0:import20.QueryList<any>;
  _query_MdHint_15_1:import20.QueryList<any>;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  compView_18:import2.AppView<import15.MdButton>;
  _MdButton_18_3:import16.Wrapper_MdButton;
  _el_19:any;
  compView_19:import2.AppView<import26.MdIcon>;
  _MdIcon_19_3:import27.Wrapper_MdIcon;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  /*private*/ _expr_50:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_AIDetailComponent1,renderType_AIDetailComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_50 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n      ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'md-card',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import14.View_MdCard0(this.viewUtils,this,2,this._el_2);
    this._MdCard_2_3 = new import14.Wrapper_MdCard();
    this._text_3 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,(null as any),'md-card-actions',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardActions_4_3 = new import14.Wrapper_MdCardActions();
    this._text_5 = this.renderer.createText(this._el_4,'\n                 ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'button',new import3.InlineArray4(4,'aria-haspopup','true','md-button',''),(null as any));
    this._vc_6 = new import11.ViewContainer(6,4,this,this._el_6);
    this.compView_6 = new import16.View_MdButton0(this.viewUtils,this,6,this._el_6);
    this._MdButton_6_5 = new import16.Wrapper_MdButton(new import12.ElementRef(this._el_6),this.renderer);
    this._MdMenuTrigger_6_6 = new import17.Wrapper_MdMenuTrigger(this.parentView.injectorGet(import28.Overlay,this.parentIndex),new import12.ElementRef(this._el_6),this._vc_6.vcRef,this.renderer,this.parentView.injectorGet(import29.Dir,this.parentIndex,(null as any)));
    this._text_7 = this.renderer.createText((null as any),' ',(null as any));
    this._text_8 = this.renderer.createText((null as any),'',(null as any));
    this.compView_6.create(this._MdButton_6_5.context);
    this._text_9 = this.renderer.createText(this._el_4,' \n\n                 ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_4,'md-menu',new import3.InlineArray2(2,'role','menu'),(null as any));
    this.compView_10 = new import19.View_MdMenu0(this.viewUtils,this,10,this._el_10);
    this._MdMenu_10_3 = new import19.Wrapper_MdMenu((null as any),(null as any));
    this._query_MdMenuItem_10_0 = new import20.QueryList<any>();
    this._text_11 = this.renderer.createText((null as any),'\n                         ',(null as any));
    this._anchor_12 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_12 = new import11.ViewContainer(12,10,this,this._anchor_12);
    this._TemplateRef_12_5 = new import30.TemplateRef_(this,12,this._anchor_12);
    this._NgFor_12_6 = new import21.Wrapper_NgFor(this._vc_12.vcRef,this._TemplateRef_12_5,this.parentView.injectorGet(import31.IterableDiffers,this.parentIndex),this.parentView.ref);
    this._text_13 = this.renderer.createText((null as any),'\n                ',(null as any));
    this.compView_10.create(this._MdMenu_10_3.context);
    this._text_14 = this.renderer.createText(this._el_4,'\n   \n           \n              ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_4,'md-input',new import3.InlineArray8(8,'max','30','min','1','type','number','value','20'),(null as any));
    this.compView_15 = new import23.View_MdInput0(this.viewUtils,this,15,this._el_15);
    this._MdInput_15_3 = new import23.Wrapper_MdInput(new import12.ElementRef(this._el_15),this.renderer);
    this._NG_VALUE_ACCESSOR_15_4 = [this._MdInput_15_3.context];
    this._NgModel_15_5 = new import24.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_15_4);
    this._NgControl_15_6 = this._NgModel_15_5.context;
    this._NgControlStatus_15_7 = new import25.Wrapper_NgControlStatus(this._NgControl_15_6);
    this._query_MdPlaceholder_15_0 = new import20.QueryList<any>();
    this._query_MdHint_15_1 = new import20.QueryList<any>();
    this._text_16 = this.renderer.createText((null as any),' ',(null as any));
    this.compView_15.create(this._MdInput_15_3.context);
    this._text_17 = this.renderer.createText(this._el_4,'\n          \n              ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_4,'button',new import3.InlineArray2(2,'md-icon-button',''),(null as any));
    this.compView_18 = new import16.View_MdButton0(this.viewUtils,this,18,this._el_18);
    this._MdButton_18_3 = new import16.Wrapper_MdButton(new import12.ElementRef(this._el_18),this.renderer);
    this._el_19 = import3.createRenderElement(this.renderer,(null as any),'md-icon',new import3.InlineArray2(2,'role','img'),(null as any));
    this.compView_19 = new import27.View_MdIcon0(this.viewUtils,this,19,this._el_19);
    this._MdIcon_19_3 = new import27.Wrapper_MdIcon(new import12.ElementRef(this._el_19),this.renderer,this.parentView.injectorGet(import32.MdIconRegistry,this.parentIndex));
    this._text_20 = this.renderer.createText((null as any),'system_update_alt',(null as any));
    this.compView_19.create(this._MdIcon_19_3.context);
    this._text_21 = this.renderer.createText((null as any),' ',(null as any));
    this.compView_18.create(this._MdButton_18_3.context);
    this._text_22 = this.renderer.createText(this._el_4,'\n          ',(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n      ',(null as any));
    this.compView_2.create(this._MdCard_2_3.context);
    this._text_24 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_6,new import3.InlineArray8(8,'mousedown',(null as any),'focus',(null as any),'blur',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_6));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_15,new import3.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_15));
    this._NgModel_15_5.subscribe(this,this.eventHandler(this.handleEvent_15),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_18,new import3.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_18));
    this._query_MdPlaceholder_15_0.reset(([] as any[]));
    this._MdInput_15_3.context._placeholderChild = this._query_MdPlaceholder_15_0.first;
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._anchor_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.MdButton) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._MdButton_6_5.context; }
    if (((token === import33.MdMenuTrigger) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._MdMenuTrigger_6_6.context; }
    if (((token === import30.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import34.NgFor) && (12 === requestNodeIndex))) { return this._NgFor_12_6.context; }
    if (((token === import18.MdMenu) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._MdMenu_10_3.context; }
    if (((token === import22.MdInput) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._MdInput_15_3.context; }
    if (((token === import35.NG_VALUE_ACCESSOR) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._NG_VALUE_ACCESSOR_15_4; }
    if (((token === import36.NgModel) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._NgModel_15_5.context; }
    if (((token === import37.NgControl) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._NgControl_15_6; }
    if (((token === import38.NgControlStatus) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._NgControlStatus_15_7.context; }
    if (((token === import26.MdIcon) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._MdIcon_19_3.context; }
    if (((token === import15.MdButton) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._MdButton_18_3.context; }
    if (((token === import13.MdCardActions) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._MdCardActions_4_3.context; }
    if (((token === import13.MdCard) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._MdCard_2_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._MdCard_2_3.ngDoCheck(this,this._el_2,throwOnChange)) { this.compView_2.markAsCheckOnce(); }
    this._MdCardActions_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    if (this._MdButton_6_5.ngDoCheck(this,this._el_6,throwOnChange)) { this.compView_6.markAsCheckOnce(); }
    const currVal_6_1_0:any = this._MdMenu_10_3.context;
    this._MdMenuTrigger_6_6.check__deprecatedMenuTriggerFor(currVal_6_1_0,throwOnChange,false);
    this._MdMenuTrigger_6_6.ngDoCheck(this,this._el_6,throwOnChange);
    this._MdMenu_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_12_0_0:any = this.parentView.context.ai.types;
    this._NgFor_12_6.check_ngForOf(currVal_12_0_0,throwOnChange,false);
    this._NgFor_12_6.ngDoCheck(this,this._anchor_12,throwOnChange);
    const currVal_15_0_0:any = '30';
    this._MdInput_15_3.check_max(currVal_15_0_0,throwOnChange,false);
    const currVal_15_0_1:any = '1';
    this._MdInput_15_3.check_min(currVal_15_0_1,throwOnChange,false);
    const currVal_15_0_2:any = 'number';
    this._MdInput_15_3.check_type(currVal_15_0_2,throwOnChange,false);
    const currVal_15_0_3:any = '20';
    this._MdInput_15_3.check_value(currVal_15_0_3,throwOnChange,false);
    this._MdInput_15_3.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_15_1_0:any = this.parentView.context.nHidden;
    this._NgModel_15_5.check_model(currVal_15_1_0,throwOnChange,false);
    this._NgModel_15_5.ngDoCheck(this,this._el_15,throwOnChange);
    this._NgControlStatus_15_7.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_18_0_0:any = false;
    this._MdButton_18_3.check_disabled(currVal_18_0_0,throwOnChange,false);
    if (this._MdButton_18_3.ngDoCheck(this,this._el_18,throwOnChange)) { this.compView_18.markAsCheckOnce(); }
    if (this._MdIcon_19_3.ngDoCheck(this,this._el_19,throwOnChange)) { this.compView_19.markAsCheckOnce(); }
    this._vc_6.detectChangesInNestedViews(throwOnChange);
    this._vc_12.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdMenuItem_10_0.dirty) {
          this._query_MdMenuItem_10_0.reset([this._vc_12.mapNestedViews(View_AIDetailComponent2,(nestedView:View_AIDetailComponent2):any => {
            return [nestedView._MdMenuItem_0_3.context];
        })]);
        this._MdMenu_10_3.context.items = this._query_MdMenuItem_10_0;
        this._query_MdMenuItem_10_0.notifyOnChanges();
      }
      if (this._query_MdHint_15_1.dirty) {
        this._query_MdHint_15_1.reset(([] as any[]));
        this._MdInput_15_3.context._hintChildren = this._query_MdHint_15_1;
        this._query_MdHint_15_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._MdMenu_10_3.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._MdInput_15_3.context.ngAfterContentInit(); }
    }
    this._MdButton_6_5.checkHost(this,this.compView_6,this._el_6,throwOnChange);
    const currVal_50:any = import3.inlineInterpolate(1,'\n                    ',this.parentView.context.aiType,'\n                 ');
    if (import3.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this.renderer.setText(this._text_8,currVal_50);
      this._expr_50 = currVal_50;
    }
    this._MdInput_15_3.checkHost(this,this.compView_15,this._el_15,throwOnChange);
    this._NgControlStatus_15_7.checkHost(this,this.compView_15,this._el_15,throwOnChange);
    this._MdButton_18_3.checkHost(this,this.compView_18,this._el_18,throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
    this.compView_6.internalDetectChanges(throwOnChange);
    this.compView_10.internalDetectChanges(throwOnChange);
    this.compView_15.internalDetectChanges(throwOnChange);
    this.compView_18.internalDetectChanges(throwOnChange);
    this.compView_19.internalDetectChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._MdMenuTrigger_6_6.context.ngAfterViewInit(); }
      this._MdIcon_19_3.context.ngAfterViewChecked();
    }
  }
  destroyInternal():void {
    this._vc_6.destroyNestedViews();
    this._vc_12.destroyNestedViews();
    this.compView_2.destroy();
    this.compView_6.destroy();
    this.compView_10.destroy();
    this.compView_15.destroy();
    this.compView_18.destroy();
    this.compView_19.destroy();
    this._MdMenuTrigger_6_6.ngOnDestroy();
    this._MdMenu_10_3.ngOnDestroy();
    this._MdInput_15_3.ngOnDestroy();
    this._NgModel_15_5.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 2) && (ngContentIndex == 0))) {
      cb(this._text_3,ctx);
      cb(this._el_4,ctx);
      cb(this._text_23,ctx);
    }
    if (((nodeIndex == 6) && (ngContentIndex == 0))) {
      cb(this._text_7,ctx);
      cb(this._text_8,ctx);
    }
    if (((nodeIndex == 10) && (ngContentIndex == 0))) {
      cb(this._text_11,ctx);
      cb(this._vc_12.nativeElement,ctx);
      this._vc_12.visitNestedViewRootNodes(cb,ctx);
      cb(this._text_13,ctx);
    }
    if (((nodeIndex == 15) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 15) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 15) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 15) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 18) && (ngContentIndex == 0))) {
      cb(this._el_19,ctx);
      cb(this._text_21,ctx);
    }
    if (((nodeIndex == 19) && (ngContentIndex == 0))) { cb(this._text_20,ctx); }
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 12)) { return new View_AIDetailComponent2(this.viewUtils,this,12,this._anchor_12,this._vc_12); }
    return (null as any);
  }
  handleEvent_6(eventName:string,$event:any):boolean {
    this.compView_6.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_6_5.handleEvent(eventName,$event) && result);
    result = (this._MdMenuTrigger_6_6.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_15(eventName:string,$event:any):boolean {
    this.compView_15.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInput_15_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.nHidden = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_18(eventName:string,$event:any):boolean {
    this.compView_18.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_18_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.implant()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_AIDetailComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_AIDetailComponent,{});
export class View_AIDetailComponent0 extends import2.AppView<import0.AIDetailComponent> {
  _anchor_0:any;
  /*private*/ _vc_0:import11.ViewContainer;
  _TemplateRef_0_5:any;
  _NgIf_0_6:import39.Wrapper_NgIf;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AIDetailComponent0,renderType_AIDetailComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_0 = new import11.ViewContainer(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import30.TemplateRef_(this,0,this._anchor_0);
    this._NgIf_0_6 = new import39.Wrapper_NgIf(this._vc_0.vcRef,this._TemplateRef_0_5);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [this._anchor_0]),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import30.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import40.NgIf) && (0 === requestNodeIndex))) { return this._NgIf_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.ai;
    this._NgIf_0_6.check_ngIf(currVal_0_0_0,throwOnChange,false);
    this._NgIf_0_6.ngDoCheck(this,this._anchor_0,throwOnChange);
    this._vc_0.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 0)) { return new View_AIDetailComponent1(this.viewUtils,this,0,this._anchor_0,this._vc_0); }
    return (null as any);
  }
}